# Generated by Django 2.2.8 on 2019-12-16 05:56

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import remark.insights.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("projects", "0078_merge_20191212_2246")]

    operations = [
        migrations.CreateModel(
            name="WeeklyInsights",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=remark.insights.models.get_weekly_insights_id,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start", models.DateField(help_text="Start date")),
                ("end", models.DateField(help_text="End date")),
                ("facts", django.contrib.postgres.fields.jsonb.JSONField()),
                ("insights", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaselineInsights",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=remark.insights.models.get_baseline_insights_id,
                        max_length=34,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start", models.DateField(help_text="Start date")),
                ("end", models.DateField(help_text="End date")),
                ("facts", django.contrib.postgres.fields.jsonb.JSONField()),
                ("insights", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                    ),
                ),
            ],
        ),
    ]
