# Generated by Django 2.2.5 on 2019-11-08 07:02

from django.db import migrations, models
import django.db.models.deletion
import remark.insights.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("projects", "0072_auto_20190919_2041")]

    operations = [
        migrations.CreateModel(
            name="BaselineInsights",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=remark.insights.models.get_baseline_insights_id,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start", models.DateField()),
                (
                    "project_id",
                    models.ForeignKey(
                        help_text="Project",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyInsights",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=remark.insights.models.get_weekly_insights_id,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("start", models.DateField()),
                (
                    "project_id",
                    models.ForeignKey(
                        help_text="Project",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WeeklyInsightsItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=remark.insights.models.get_weekly_insights_item_id,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("insight_id", models.CharField(max_length=256)),
                (
                    "modifier_id",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("insight_text", models.TextField()),
                ("insight_data", models.TextField()),
                ("priority", models.IntegerField()),
                (
                    "weekly_insights_id",
                    models.ForeignKey(
                        help_text="Weekly Insights",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insights.WeeklyInsights",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BaselineInsightsItem",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=remark.insights.models.get_baseline_insights_item_id,
                        max_length=32,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("insight_id", models.CharField(max_length=256)),
                (
                    "modifier_id",
                    models.CharField(blank=True, max_length=256, null=True),
                ),
                ("insight_text", models.TextField()),
                ("insight_data", models.TextField()),
                ("priority", models.IntegerField()),
                (
                    "baseline_insights_id",
                    models.ForeignKey(
                        help_text="Baseline Insights",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="insights.BaselineInsights",
                    ),
                ),
            ],
        ),
    ]
