# Generated by Django 2.2.8 on 2020-01-14 15:35

import django.contrib.postgres.fields.jsonb
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion
import remark.insights.models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0079_auto_20200107_1835"),
        ("insights", "0002_fix_insights_data_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="PerformanceInsights",
            fields=[
                ("start", models.DateField(help_text="Start date")),
                ("end", models.DateField(help_text="End date")),
                (
                    "facts",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "insights",
                    django.contrib.postgres.fields.jsonb.JSONField(
                        encoder=django.core.serializers.json.DjangoJSONEncoder
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=remark.insights.models.get_performance_insights_id,
                        max_length=37,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projects.Project",
                    ),
                ),
            ],
            options={"abstract": False},
        )
    ]
