# Generated by Django 2.2.9 on 2020-01-30 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0003_add_performance_insights'),
        ('insights', '0002_auto_20200123_1926'),
    ]

    operations = [
    ]
