# Generated by Django 2.2.9 on 2020-02-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0004_merge_20200130_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=62)),
                ('description', models.TextField(blank=True, null=True)),
                ('include_in_email', models.BooleanField(default=True)),
                ('priority_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['priority_order'],
            },
        ),
    ]
