# Generated by Django 2.2.10 on 2020-02-18 7:57

from django.db import migrations, models
import django.db.models.deletion
import remark.insights.models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0005_insight'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedActionTactic',
            fields=[
                ('public_id', models.CharField(default=remark.insights.models.get_suggested_action_tactic_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=160)),
            ],
        ),
        migrations.CreateModel(
            name='SuggestedAction',
            fields=[
                ('public_id', models.CharField(default=remark.insights.models.get_suggested_action_id, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=160)),
                ('tactics', models.ManyToManyField(blank=True, to='insights.SuggestedActionTactic')),
            ],
        ),
        migrations.CreateModel(
            name='KPI',
            fields=[
                ('public_id', models.CharField(default=remark.insights.models.get_kpi_id, editable=False, max_length=24, primary_key=True, serialize=False)),
                ('name', models.TextField(choices=[('leased', 'Leased'), ('retention', 'Retention'), ('occupied', 'Occupied'), ('app', 'Lease Applications / Volume of APP'), ('cds', 'Cancellations & Denials'), ('renew', 'Notices to Renew'), ('vacate', 'Notices to Vacate'), ('move_ins', 'Move Ins'), ('move_outs', 'Move Outs'), ('investment', 'Campaign Investment'), ('acq_investment', 'Acquisition Investment'), ('acq_romi', 'Acquisition ROMI'), ('lease_renewals', 'Lease Renewals'), ('ret_investment', 'Retention Investment'), ('ret_romi', 'Retention ROMI'), ('usv_exe', 'USV > EXE'), ('lowest_monthly_rent', 'Cost Per EXE / Lowest Monthly Rent'), ('usv', 'Volume of USV'), ('inq', 'Volume of INQ'), ('tou', 'Volume of TOU'), ('exe', 'Volume of EXE'), ('usv_inq', 'USV > INQ'), ('inq_tou', 'INQ > TOU'), ('tou_app', 'TOU > APP'), ('app_exe', 'APP > EXE'), ('cost_per_usv', 'Cost per USV'), ('cost_per_inq', 'Cost per INQ'), ('cost_per_tou', 'Cost per TOU'), ('cost_per_app', 'Cost per APP'), ('cost_per_exe', 'Cost per EXE')], help_text='KPI name, user cannot edit')),
                ('definition', models.CharField(blank=True, help_text='KPI Definition', max_length=255, null=True)),
                ('baseline_category_1_action', models.OneToOneField(blank=True, help_text='Suggested Action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='insights.SuggestedAction', verbose_name='Baseline - Category 1')),
                ('baseline_category_2_action', models.OneToOneField(blank=True, help_text='Suggested Action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='insights.SuggestedAction', verbose_name='Baseline - Category 2')),
                ('off_track_category_1_action', models.OneToOneField(blank=True, help_text='Suggested Action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='insights.SuggestedAction', verbose_name='Off Track/At Risk - Category 1')),
                ('off_track_category_2_action', models.OneToOneField(blank=True, help_text='Suggested Action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='insights.SuggestedAction', verbose_name='Off Track/At Risk - Category 2')),
                ('on_track_category_1_action', models.OneToOneField(blank=True, help_text='Suggested Action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='insights.SuggestedAction', verbose_name='On Track - Category 1')),
                ('on_track_category_2_action', models.OneToOneField(blank=True, help_text='Suggested Action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='insights.SuggestedAction', verbose_name='On Track - Category 2')),
            ],
        ),
    ]
