# Generated by Django 2.2.10 on 2020-02-20 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0009_auto_20200220_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kpi',
            name='baseline_category_1_action',
            field=models.ForeignKey(blank=True, help_text='Suggested Action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='insights.SuggestedAction', verbose_name='Baseline - Category 1'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='baseline_category_2_action',
            field=models.ForeignKey(blank=True, help_text='Suggested Action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='insights.SuggestedAction', verbose_name='Baseline - Category 2'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='off_track_category_1_action',
            field=models.ForeignKey(blank=True, help_text='Suggested Action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='insights.SuggestedAction', verbose_name='Off Track/At Risk - Category 1'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='off_track_category_2_action',
            field=models.ForeignKey(blank=True, help_text='Suggested Action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='insights.SuggestedAction', verbose_name='Off Track/At Risk - Category 2'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='on_track_category_1_action',
            field=models.ForeignKey(blank=True, help_text='Suggested Action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='insights.SuggestedAction', verbose_name='On Track - Category 1'),
        ),
        migrations.AlterField(
            model_name='kpi',
            name='on_track_category_2_action',
            field=models.ForeignKey(blank=True, help_text='Suggested Action', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='insights.SuggestedAction', verbose_name='On Track - Category 2'),
        ),
    ]
