# Generated by Django 2.2.2 on 2019-06-13 23:52

from django.db import migrations, models
import django.db.models.deletion
import remark.crm.models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0012_add_has_population_to_zipcode'),
        ('crm', '0001_add_business_model'),
        ('projects', '0037_add_business_and_foud_to_project')
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('public_id', models.CharField(default=remark.crm.models.off_public_id, editable=False, help_text='A unique identifier for this person that is safe to share publicly.', max_length=24, primary_key=True, serialize=False)),
                ('is_home_office', models.BooleanField(default=False, help_text='Is the home office?')),
                ('name', models.CharField(default='', help_text='Office Name', max_length=255)),
                ('address', models.ForeignKey(help_text='Address', on_delete=django.db.models.deletion.CASCADE, to='geo.Address')),
            ],
        ),
        migrations.RemoveField(
            model_name='business',
            name='address',
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('public_id', models.CharField(default=remark.crm.models.peep_public_id, editable=False, help_text='A unique identifier for this person that is safe to share publicly.', max_length=24, primary_key=True, serialize=False)),
                ('first_name', models.CharField(help_text='First Name', max_length=255)),
                ('last_name', models.CharField(help_text='Last Name', max_length=255)),
                ('role', models.CharField(help_text='Job Role', max_length=255)),
                ('email', models.CharField(help_text='Email', max_length=255)),
                ('office_phone', models.CharField(help_text='Office Phone', max_length=255)),
                ('cell_phone', models.CharField(help_text='Cell Phone', max_length=255)),
                ('office', models.ForeignKey(help_text='Office the person works at', on_delete=django.db.models.deletion.CASCADE, to='crm.Office')),
            ],
        ),
        migrations.AddField(
            model_name='office',
            name='business',
            field=models.ForeignKey(help_text='Business', on_delete=django.db.models.deletion.CASCADE, to='crm.Business'),
        ),
    ]
