# Generated by Django 2.2.2 on 2019-06-20 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import remark.crm.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crm', '0002_auto_20190613_2352'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, default='', help_text='A full-resolution user avatar.<br/>Resized variants (100x100, 36x36) will also be created on Amazon S3.', null=True, upload_to=remark.crm.models.avatar_media_path),
        ),
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.ForeignKey(help_text='User associated with this person', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
