# Generated by Django 2.2.2 on 2019-06-21 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20190620_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cell_phone',
            field=models.CharField(blank=True, help_text='Cell Phone', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='office_phone',
            field=models.CharField(blank=True, help_text='Office Phone', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='user',
            field=models.ForeignKey(blank=True, help_text='User associated with this person', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
