# Generated by Django 2.2.3 on 2019-07-12 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0005_allow_business_multitype")]

    operations = [
        migrations.AddField(
            model_name="business",
            name="is_developer",
            field=models.BooleanField(
                default=False, help_text="Business Type is Developer"
            ),
        )
    ]
