# Generated by Django 2.2.4 on 2019-08-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0006_add_developer_business_type")]

    operations = [
        migrations.AddField(
            model_name="office",
            name="office_type",
            field=models.IntegerField(
                blank=True,
                choices=[(1, "Global"), (2, "National"), (3, "Regional"), (4, "Other")],
                help_text="Office Type",
                null=True,
            ),
        )
    ]
