# Generated by Django 2.2.5 on 2019-10-17 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("crm", "0007_add_office_type")]

    operations = [
        migrations.AddField(
            model_name="business",
            name="is_investor",
            field=models.BooleanField(
                default=False, help_text="Business Type is JV / Investor"
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="is_vendor",
            field=models.BooleanField(
                default=False, help_text="Business Type is Vendor / Consultant"
            ),
        ),
    ]
