# Generated by Django 2.2.9 on 2020-01-24 10:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_make_office_nullable_in_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='address',
            field=models.ForeignKey(help_text='Address', null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.Address'),
        ),
        migrations.AlterField(
            model_name='office',
            name='business',
            field=models.ForeignKey(help_text='Business', null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.Business'),
        ),
        migrations.AlterField(
            model_name='office',
            name='name',
            field=models.CharField(default='', help_text='Office Name', max_length=255, null=True),
        ),
    ]
