version: "2.1"

services:
  redis:
    image: 'redis:5.0.5'

  postgres:
    image: postgres:9.6
    environment:
      - POSTGRES_USER=airflow
      - POSTGRES_PASSWORD=airflow
      - POSTGRES_DB=airflow
    expose:
      - "5432"
    ports:
      - "5432:5432"

  web:
    environment:
        - DOCKER_COMPOSE=true
        - LOCAL_AIRFLOW=true
        - LC_ALL=C.UTF-8
        - LANG=C.UTF-8
    build: .
    command: >
        bash -c "pipenv run python manage.py migrate &&
                 pipenv run python manage.py loaddata data/dumped/latest.json &&
                 npm rebuild node-sass &&
                 nohup yarn run run-build-ui > out.log &
                 pipenv run python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
      - "8090:8090"
    depends_on:
      - redis
      - postgres

  webserver:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
      - postgres
      - redis
    env_file:
      - .env
    environment:
      - DOCKER_COMPOSE=true
      - LOAD_EX=n
      - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
      - EXECUTOR=Celery
      - LOCAL_AIRFLOW=true
      - POSTGRES_PASSWORD=airflow
      - AIRFLOW_PATHING=true
    volumes:
      - ./airflow_requirements.txt:/requirements.txt
      - ./remark_airflow/dags:/usr/local/airflow/dags
      - ./remark:/usr/local/airflow/dags/remark
      - ./data:/usr/local/airflow/dags/data
      - ./xls:/usr/local/airflow/dags/xls
      - ./remark_airflow/insights:/usr/local/airflow/dags/remark_airflow/insights
      # Uncomment to include custom plugins
      # - ./plugins:/usr/local/airflow/plugins
    ports:
      - "8080:8080"
    command: webserver
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/local/airflow/airflow-webserver.pid ]"]
      interval: 30s
      timeout: 30s
      retries: 3

  flower:
    image: puckel/docker-airflow:1.10.7
    restart: always
    depends_on:
        - redis
    environment:
        - EXECUTOR=Celery
        # - REDIS_PASSWORD=redispass
    ports:
        - "5555:5555"
    command: flower

  scheduler:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
        - webserver
    env_file:
        - .env
    volumes:
        - ./remark_airflow/dags:/usr/local/airflow/dags
        - ./airflow_requirements.txt:/requirements.txt
        - ./remark:/usr/local/airflow/dags/remark
        - ./data:/usr/local/airflow/dags/data
        - ./xls:/usr/local/airflow/dags/xls
        - ./remark_airflow/insights:/usr/local/airflow/dags/remark_airflow/insights
        # Uncomment to include custom plugins
        # - ./plugins:/usr/local/airflow/plugins
    environment:
        - LOAD_EX=n
        - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - EXECUTOR=Celery
        - DOCKER_COMPOSE=true
        - LOCAL_AIRFLOW=true
        - POSTGRES_PASSWORD=airflow
        - AIRFLOW_PATHING=true
    command: scheduler

  worker:
    image: puckel/docker-airflow:1.10.4
    restart: always
    depends_on:
        - scheduler
    env_file:
        - .env
    volumes:
        - ./remark_airflow/dags:/usr/local/airflow/dags
        - ./airflow_requirements.txt:/requirements.txt
        - ./remark:/usr/local/airflow/dags/remark
        - ./data:/usr/local/airflow/dags/data
        - ./xls:/usr/local/airflow/dags/xls
        - ./remark_airflow/insights:/usr/local/airflow/dags/remark_airflow/insights
        # Uncomment to include custom plugins
        # - ./plugins:/usr/local/airflow/plugins
    environment:
        - FERNET_KEY=46BKJoQYlPPOexq0OhDZnIlNepKFf87WFwLbfzqDDho=
        - EXECUTOR=Celery
        - DOCKER_COMPOSE=true
        - LOCAL_AIRFLOW=true
        - POSTGRES_PASSWORD=airflow
        - AIRFLOW_PATHING=true
    command: worker
