# Generated by Django 2.1.5 on 2019-02-05 22:23

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import remark.lib.metrics
import remark.projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(db_index=True, help_text='The first date, inclusive, that this period tracks.')),
                ('end', models.DateField(db_index=True, help_text='The final date, exclusive, that this period tracks.')),
                ('occupiable_units_start', models.IntegerField(default=0, help_text='The number of units that can be occupied at the start of this period.')),
                ('leased_units_start', models.IntegerField(default=0, help_text='The absolute number of leased units at the start of this period.')),
                ('leases_ended', models.IntegerField(default=0, help_text='The number of leases ended (expired) during this period.')),
                ('leases_executed', models.IntegerField(default=0, help_text='The number of new leases (not applications) executed during this period.')),
                ('lease_applications', models.IntegerField(default=0, help_text='The number of lease applications during this period.')),
                ('target_lease_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='The target percentage of leasable units that we would like to actually lease. (Enter 0.9 for 90%)', max_digits=4)),
                ('leases_renewed', models.IntegerField(default=0, help_text='The number of lease renewals signed in the period.')),
                ('leasable_units', models.IntegerField(default=0, help_text='The number of units that *are* or *can* be leased at the end of this period.')),
                ('usvs', models.IntegerField(default=0, help_text='The number of unique site visitors during this period.')),
                ('inquiries', models.IntegerField(default=0, help_text='The number of site inquiries during this period.')),
                ('tours', models.IntegerField(default=0, help_text='The number of tours during this period.')),
                ('previous_leased_rate', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='The leased rate as percentage of leasable for the previous period. (Enter 0.9 for 90%)', max_digits=4)),
                ('investment_reputation_building', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The dollar amount invested in reputation building during this period.', max_digits=10)),
                ('investment_demand_creation', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The dollar amount invested in demand creation during this period.', max_digits=10)),
                ('investment_leasing_enablement', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The dollar amount invested in leasing enablement during this period.', max_digits=10)),
                ('investment_market_intelligence', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The dollar amount invested in market intelligence during this period.', max_digits=10)),
                ('investment_resident_retention', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The dollar amount invested in resident retention during this period.', max_digits=10)),
                ('monthly_average_rent', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='The average rent tenants pay in any given month.', max_digits=10)),
                ('leases_executed_goal', models.IntegerField(default=0, help_text='The period goal for number of new leases executed during this period.')),
                ('leases_renewed_goal', models.IntegerField(default=0, help_text='The period goal for number of lease renewals signed in the period.')),
                ('leases_ended_goal', models.IntegerField(default=0, help_text='The period goal for number of leases ended (expired) during this period.')),
                ('net_lease_change_goal', models.IntegerField(default=0, help_text='The period goal for net number of new leases during this period.')),
                ('usvs_goal', models.IntegerField(default=0, help_text='The goal for number of unique site visitors during this period.')),
                ('inquiries_goal', models.IntegerField(default=0, help_text='The goal for number of site inquiries during this period.')),
                ('tours_goal', models.IntegerField(default=0, help_text='The goal for number of tours during this period.')),
                ('lease_applications_goal', models.IntegerField(default=0, help_text='The goal_for number of lease applications during this period.')),
                ('usvs_to_inquiries_percent_goal', models.DecimalField(decimal_places=2, default=0, help_text='The goal for conversation rate from usvs to inquiries.', max_digits=10)),
                ('inquiries_to_tours_percent_goal', models.DecimalField(decimal_places=2, default=0, help_text='The goal for conversion rate from inquiries to tours.', max_digits=10)),
                ('tours_to_lease_applications_percent_goal', models.DecimalField(decimal_places=2, default=0, help_text='The goal for conversion rate from lease applications to tours.', max_digits=10)),
                ('lease_applications_to_leases_executed_percent_goal', models.DecimalField(decimal_places=2, default=0, help_text='The goal for conversion rate from lease executions to tours.', max_digits=10)),
                ('marketing_investment_goal', models.DecimalField(decimal_places=2, default=0, help_text='Return the total marketing investment in this period, across all categories.', max_digits=10)),
                ('return_on_marketing_investment_goal', models.DecimalField(decimal_places=2, default=0, help_text='Goal for return on marketing investment.', max_digits=10)),
                ('estimated_annual_revenue_change_goal', models.DecimalField(decimal_places=2, default=0, help_text='Goal for estimated annual revenue change', max_digits=10)),
            ],
            options={
                'ordering': ['start'],
            },
            bases=(remark.lib.metrics.ModelPeriodBase, models.Model),
        ),
        migrations.CreateModel(
            name='PeriodManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(remark.lib.metrics.ModelPeriodSetBase, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('public_id', models.CharField(default=remark.projects.models.pro_public_id, editable=False, help_text='A unique identifier for this project that is safe to share publicly.', max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The user-facing name of the project.', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='period',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='projects.Project'),
        ),
    ]
