# Generated by Django 2.1.5 on 2019-02-13 19:03

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import remark.lib.metrics
import remark.projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(db_index=True, help_text='The first date, inclusive, that this period tracks.')),
                ('end', models.DateField(db_index=True, help_text='The final date, exclusive, that this period tracks.')),
                ('leased_units_start', models.IntegerField(blank=True, default=None, help_text='Number of leased units at period start. If not specified, will be pulled from a previous period.', null=True)),
                ('leases_ended', models.IntegerField(default=0, help_text='Number of leases ended (roughly: move outs)')),
                ('lease_applications', models.IntegerField(default=0, help_text='Number of lease applications')),
                ('leases_executed', models.IntegerField(default=0, help_text='Number of new leases executed')),
                ('lease_cds', models.IntegerField(default=0, help_text='Number of lease cancellations and denials')),
                ('leases_due_to_expire', models.IntegerField(default=0, help_text='Number of leases due to expire in period')),
                ('lease_renewal_notices', models.IntegerField(default=0, help_text='Number of lease renewals signed')),
                ('lease_renewals', models.IntegerField(default=0, help_text='Number of lease renewals that took effect')),
                ('lease_vacation_notices', models.IntegerField(default=0, help_text='Number of notices to vacate leases')),
                ('target_lease_percent', models.DecimalField(blank=True, decimal_places=3, default=None, help_text='Target: lease percentage (like 0.9)', max_digits=4, null=True)),
                ('target_lease_applications', models.IntegerField(blank=True, default=None, help_text='Target: lease applications', null=True)),
                ('target_leases_executed', models.IntegerField(blank=True, default=None, help_text='Target: leases execfuted', null=True)),
                ('target_lease_renewal_notices', models.IntegerField(blank=True, default=None, help_text='Target: lease renewal notices', null=True)),
                ('target_leases_due_to_expire', models.IntegerField(blank=True, default=None, help_text='Target: leases due to expire', null=True)),
                ('target_lease_renewals', models.IntegerField(blank=True, default=None, help_text='Target: lease renewals', null=True)),
                ('target_lease_vacation_notices', models.IntegerField(blank=True, default=None, help_text='Target: lease vacation notices', null=True)),
                ('target_lease_cds', models.IntegerField(blank=True, default=None, help_text='Target: lease cancellations and denials', null=True)),
                ('target_delta_leases', models.IntegerField(blank=True, default=None, help_text='Target: delta: leases', null=True)),
                ('occupiable_units_start', models.IntegerField(blank=True, default=None, help_text='Number of units that can possibly be at period start. If not specified, will be pulled from a previous period.', null=True)),
                ('occupied_units_start', models.IntegerField(blank=True, default=0, help_text='Number of units occupied at period start. If not specified, will be pulled from a previous period.', null=True)),
                ('move_ins', models.IntegerField(default=0, help_text='Number of units moved into')),
                ('move_outs', models.IntegerField(default=0, help_text='Number of units moved out of')),
                ('target_move_ins', models.IntegerField(blank=True, default=None, help_text='Target: move ins', null=True)),
                ('target_move_outs', models.IntegerField(blank=True, default=None, help_text='Target: move outs', null=True)),
                ('acq_reputation_building', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in acquisition reputation building', max_digits=10)),
                ('acq_demand_creation', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in acquisition demand creation', max_digits=10)),
                ('acq_leasing_enablement', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in acquisition leasing enablement', max_digits=10)),
                ('acq_market_intelligence', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in acquisition market intelligence', max_digits=10)),
                ('monthly_average_rent', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Average rent tenants pay in the month including this period. If not specified, it will be pulled from an earlier period.', max_digits=10, null=True)),
                ('target_acq_investment', models.DecimalField(decimal_places=2, default=None, help_text='Target: total acquisition investment', max_digits=10, null=True)),
                ('ret_reputation_building', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in retention reputation building', max_digits=10)),
                ('ret_demand_creation', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in retention demand creation', max_digits=10)),
                ('ret_leasing_enablement', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in retention leasing enablement', max_digits=10)),
                ('ret_market_intelligence', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in retention market intelligence', max_digits=10)),
                ('target_ret_investment', models.DecimalField(decimal_places=2, default=None, help_text='Target: total retention investment', max_digits=10, null=True)),
                ('usvs', models.IntegerField(default=0, help_text='The number of unique site visitors during this period.')),
                ('inquiries', models.IntegerField(default=0, help_text='The number of site inquiries during this period.')),
                ('tours', models.IntegerField(default=0, help_text='The number of tours during this period.')),
                ('target_usvs', models.IntegerField(blank=True, default=None, help_text='Target: USVs', null=True)),
                ('target_inquiries', models.IntegerField(blank=True, default=None, help_text='Target: INQs', null=True)),
                ('target_tours', models.IntegerField(blank=True, default=None, help_text='Target: tours', null=True)),
            ],
            options={
                'ordering': ['start'],
            },
            bases=(remark.lib.metrics.ModelPeriod, models.Model),
        ),
        migrations.CreateModel(
            name='PeriodManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            bases=(remark.lib.metrics.ModelPeriodSet, models.Model),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('public_id', models.CharField(default=remark.projects.models.pro_public_id, editable=False, help_text='A unique identifier for this project that is safe to share publicly.', max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The user-facing name of the project.', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='period',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='projects.Project'),
        ),
    ]
