# Generated by Django 2.1.4 on 2018-12-22 01:04

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import remark.projects.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(db_index=True, help_text='The first date, inclusive, that this period tracks.')),
                ('end', models.DateField(db_index=True, help_text='The final date, inclusive, that this period tracks.')),
                ('leased_units_start', models.IntegerField(default=0, help_text='The absolute number of leased units at the start of this period.')),
                ('usvs', models.IntegerField(default=0, help_text='The number of unique site visitors during this period.')),
                ('inquiries', models.IntegerField(default=0, help_text='The number of site inquiries during this period.')),
                ('tours', models.IntegerField(default=0, help_text='The number of tours during this period.')),
                ('lease_applications', models.IntegerField(default=0, help_text='The number of lease applications during this period.')),
                ('lease_executions', models.IntegerField(default=0, help_text='The number of new leases executed during this period.')),
                ('leasable_units', models.IntegerField(default=0, help_text='The number of units that *are* or *can* be leased at the end of this period.')),
                ('target_lease_percent', models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='The target percentage of leasable units that we would like to actually lease.', max_digits=4)),
                ('move_ins', models.IntegerField(default=0, help_text='The number of units moved into during this period.')),
                ('lease_terminations', models.IntegerField(default=0, help_text='The number of leases terminated during this period.')),
                ('renewals', models.IntegerField(default=0, help_text='The number of lease renewals signed in the period.')),
                ('occupied_units', models.IntegerField(default=0, help_text='The number of units occupied at the end of this period.')),
                ('move_outs', models.IntegerField(default=0, help_text='The number of units moved out from during this period.')),
                ('investment_reputation_building', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The dollar amount invested in reputation building during this period.', max_digits=10)),
                ('investment_demand_creation', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The dollar amount invested in demand creation during this period.', max_digits=10)),
                ('investment_leasing_enablement', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The dollar amount invested in leasing enablement during this period.', max_digits=10)),
                ('investment_market_intelligence', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The dollar amount invested in market intelligence during this period.', max_digits=10)),
                ('investment_other', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The dollar amount invested in other marketing during this period.', max_digits=10)),
                ('monthly_average_rent', models.DecimalField(decimal_places=2, default=Decimal('1'), help_text='The average rent tenants pay in any given month.', max_digits=10)),
            ],
            options={
                'ordering': ['start'],
            },
        ),
        migrations.CreateModel(
            name='PeriodManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('public_id', models.CharField(default=remark.projects.models.pro_public_id, editable=False, help_text='A unique identifier for this project that is safe to share publicly.', max_length=24, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The user-facing name of the project.', max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='period',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='projects.Project'),
        ),
    ]
