# Generated by Django 2.1.4 on 2019-01-04 21:34

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='period',
            old_name='lease_executions',
            new_name='leases_executed',
        ),
        migrations.RenameField(
            model_name='period',
            old_name='renewals',
            new_name='leases_renewed',
        ),
        migrations.RemoveField(
            model_name='period',
            name='investment_other',
        ),
        migrations.RemoveField(
            model_name='period',
            name='lease_terminations',
        ),
        migrations.RemoveField(
            model_name='period',
            name='move_ins',
        ),
        migrations.RemoveField(
            model_name='period',
            name='move_outs',
        ),
        migrations.RemoveField(
            model_name='period',
            name='occupied_units',
        ),
        migrations.AddField(
            model_name='period',
            name='investment_resident_retention',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='The dollar amount invested in resident retention during this period.', max_digits=10),
        ),
        migrations.AddField(
            model_name='period',
            name='leases_ended',
            field=models.IntegerField(default=0, help_text='The number of ended (expired) during this period.'),
        ),
        migrations.AddField(
            model_name='period',
            name='previous_leased_rate',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='The leased rate as percentage of leasable for the previous period. (Enter 0.9 for 90%)', max_digits=4),
        ),
        migrations.AlterField(
            model_name='period',
            name='target_lease_percent',
            field=models.DecimalField(decimal_places=3, default=Decimal('0'), help_text='The target percentage of leasable units that we would like to actually lease. (Enter 0.9 for 90%)', max_digits=4),
        ),
    ]
