# Generated by Django 2.1.7 on 2019-03-04 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='baseline_end',
            field=models.DateField(blank=True, default=None, help_text='The final date, exclusive, for the baseline period.', null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='baseline_start',
            field=models.DateField(blank=True, default=None, help_text='The first date, inclusive, for the baseline period.', null=True),
        ),
    ]
