# Generated by Django 2.1.5 on 2019-01-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20190104_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='estimated_annual_revenue_change_goal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Goal for estimated annual revenue change', max_digits=10),
        ),
        migrations.AddField(
            model_name='period',
            name='inquiries_goal',
            field=models.IntegerField(default=0, help_text='The goal for number of site inquiries during this period.'),
        ),
        migrations.AddField(
            model_name='period',
            name='inquiries_to_tours_percent_goal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The goal for conversion rate from inquiries to tours.', max_digits=10),
        ),
        migrations.AddField(
            model_name='period',
            name='lease_applications_goal',
            field=models.IntegerField(default=0, help_text='The goal_for number of lease applications during this period.'),
        ),
        migrations.AddField(
            model_name='period',
            name='lease_applications_to_leases_executed_percent_goal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The goal for conversion rate from lease executions to tours.', max_digits=10),
        ),
        migrations.AddField(
            model_name='period',
            name='leases_ended_goal',
            field=models.IntegerField(default=0, help_text='The period goal for number of leases ended (expired) during this period.'),
        ),
        migrations.AddField(
            model_name='period',
            name='leases_executed_goal',
            field=models.IntegerField(default=0, help_text='The period goal for number of new leases executed during this period.'),
        ),
        migrations.AddField(
            model_name='period',
            name='leases_renewed_goal',
            field=models.IntegerField(default=0, help_text='The period goal for number of lease renewals signed in the period.'),
        ),
        migrations.AddField(
            model_name='period',
            name='marketing_investment_goal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Return the total marketing investment in this period, across all categories.', max_digits=10),
        ),
        migrations.AddField(
            model_name='period',
            name='net_lease_change_goal',
            field=models.IntegerField(default=0, help_text='The net number of new leases during this period.'),
        ),
        migrations.AddField(
            model_name='period',
            name='return_on_marketing_investment_goal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Goal for return on marketing investment.', max_digits=10),
        ),
        migrations.AddField(
            model_name='period',
            name='tours_goal',
            field=models.IntegerField(default=0, help_text='The goal for number of tours during this period.'),
        ),
        migrations.AddField(
            model_name='period',
            name='tours_to_lease_applications_percent_goal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The goal for conversion rate from lease applications to tours.', max_digits=10),
        ),
        migrations.AddField(
            model_name='period',
            name='usvs_goal',
            field=models.IntegerField(default=0, help_text='The goal for number of unique site visitors during this period.'),
        ),
        migrations.AddField(
            model_name='period',
            name='usvs_to_inquiries_percent_goal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The goal for conversation rate from usvs to inquiries.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='period',
            name='leases_ended',
            field=models.IntegerField(default=0, help_text='The number of leases ended (expired) during this period.'),
        ),
        migrations.AlterField(
            model_name='period',
            name='leases_executed',
            field=models.IntegerField(default=0, help_text='The number of new leases (not applications) executed during this period.'),
        ),
    ]
