# Generated by Django 2.1.7 on 2019-03-04 21:26

from django.db import migrations


def assign_dates(apps, schema_editor):
    # Prior to this migration, we assume that every project has a single
    # baseline period -- the first. Post migration, we assume that a project
    # can have any number of baseline periods, explicitly declared on the
    # Project itself.
    Project = apps.get_model("projects", "Project")
    Period = apps.get_model("projects", "Period")
    for project in Project.objects.all():
        baseline_period = Period.objects.filter(project=project).first()
        project.baseline_start = baseline_period.start
        project.baseline_end = baseline_period.end
        project.save()


class Migration(migrations.Migration):

    dependencies = [("projects", "0002_add_explicit_nullable_baseline_dates")]

    operations = [migrations.RunPython(assign_dates)]
