# Generated by Django 2.1.7 on 2019-03-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_assign_initial_baseline_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='baseline_end',
            field=models.DateField(help_text='The final date, exclusive, for the baseline period.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='baseline_start',
            field=models.DateField(help_text='The first date, inclusive, for the baseline period.'),
        ),
    ]
