# Generated by Django 2.1.7 on 2019-03-05 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_nullability_from_project_baseline_dates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='target_acq_investment',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Target: total acquisition investment', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='target_ret_investment',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Target: total retention investment', max_digits=10, null=True),
        ),
    ]
