# Generated by Django 2.1.7 on 2019-03-05 21:38

from django.db import migrations, models


def move_over_average_monthly(apps, schema_editor):
    """
    Copy the average monthly rent (if set) into the lowest rent value,
    to allow for stability in our reporting. After this migration, it's
    fine for us to go back and manually enter new numbers for lowest rent.
    """
    Period = apps.get_model("projects", "Period")
    for period in Period.objects.all():
        period.lowest_monthly_rent = period.monthly_average_rent
        period.save()


class Migration(migrations.Migration):

    dependencies = [("projects", "0005_allow_blank_target_investment_values")]

    operations = [
        migrations.AddField(
            model_name="period",
            name="lowest_monthly_rent",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=None,
                help_text="Lowest rent tenants pay in the month including this period. If not specified, it will be pulled from an earlier period.",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.RunPython(move_over_average_monthly),
    ]
