# Generated by Django 2.1.7 on 2019-03-06 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_add_tmp_json_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='tmp_market_analysis_json',
            new_name='tmp_market_report_json',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='tmp_model_options_json',
            new_name='tmp_modeling_report_json',
        ),
    ]
