# Generated by Django 2.1.7 on 2019-03-25 21:19

from django.db import migrations

from remark.lib.math import sum_or_none

# leased_units_start
# occupied_units_start


def force_periods(periods):
    """
    For each period, make sure its point values are computed.
    """
    # Skip empty period lists.
    periods = list(periods)
    if not periods:
        return

    leased_units_start = None
    occupied_units_start = None

    for period in periods:
        period.leased_units_start = (
            period.leased_units_start
            if period.leased_units_start is not None
            else leased_units_start
        )
        period.occupied_units_start = (
            period.occupied_units_start
            if period.occupied_units_start is not None
            else occupied_units_start
        )

        period.save()

        leased_units_start = sum_or_none(
            period.leased_units_start, period.leases_executed, -period.leases_ended
        )
        occupied_units_start = sum_or_none(
            period.occupied_units_start, period.move_ins, -period.move_outs
        )


def force_projects(apps, schema_editor):
    """
    For each project, force each of its periods to have a start PIT value
    that matches the previous.
    """
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all():
        periods = project.periods.all().order_by("start")
        force_periods(periods)


class Migration(migrations.Migration):

    dependencies = [("projects", "0008_rename_tmp_json_fields")]

    operations = [migrations.RunPython(force_projects)]

