# Generated by Django 2.1.7 on 2019-03-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_force_point_in_time_starting_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='period',
            name='leased_units_start',
            field=models.IntegerField(help_text='Number of leased units at period start.'),
        ),
        migrations.AlterField(
            model_name='period',
            name='occupied_units_start',
            field=models.IntegerField(help_text='Number of units occupied at period start.'),
        ),
    ]
