# Generated by Django 2.1.7 on 2019-03-26 20:51

from django.db import migrations, models
import remark.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_require_leasing_occupied_each_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='building_image',
            field=models.ImageField(blank=True, default='', help_text='A full-resolution user-supplied image of the building.', upload_to=remark.projects.models.building_image_media_path),
        ),
    ]
