# Generated by Django 2.1.7 on 2019-04-01 20:07

from django.db import migrations
import remark.projects.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_add_building_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='building_image',
            field=stdimage.models.StdImageField(blank=True, default='', help_text='A full-resolution user-supplied image of the building.<br/>Resized variants (180x180, 76x76) will also be created on Amazon S3.', upload_to=remark.projects.models.building_logo_media_path),
        ),
    ]
