# Generated by Django 2.1.7 on 2019-03-29 16:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import remark.projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0011_add_building_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The creation date for this spreadsheet record.')),
                ('file', models.FileField(help_text='The underlying spreadsheet (probably .xlsx) file.', upload_to=remark.projects.models.spreadsheet_media_path)),
                ('kind', models.CharField(choices=[('periods', 'periods'), ('modeling-run-rate', 'modeling (run rate)'), ('modeling-schedule', 'modeling (schedule driven)'), ('modeling-investment', 'modeling (investment driven)'), ('market', 'market')], db_index=True, help_text='The kind of data this spreadsheet contains.', max_length=128)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheets', to='projects.Project')),
                ('user', models.ForeignKey(blank=True, default=None, help_text='The user that uploaded this version of the spreadsheet.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='spreadsheet',
            index=models.Index(fields=['created', 'kind'], name='projects_sp_created_8ef1da_idx'),
        ),
    ]
