# Generated by Django 2.1.7 on 2019-03-27 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_add_building_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='building_image_original',
            field=models.URLField(blank=True, default='', help_text='Original version of user-supplied image of the building', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='building_image_regular',
            field=models.URLField(blank=True, default='', help_text='180x180 version of user-supplied image of the building', max_length=500),
        ),
        migrations.AddField(
            model_name='project',
            name='building_image_thumbnail',
            field=models.URLField(blank=True, default='', help_text='76x76 version of user-supplied image of the building', max_length=500),
        ),
    ]
