# Generated by Django 2.1.7 on 2019-04-01 20:08

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_convert_building_image_to_stdimagefield'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tmp_campaign_plan_json',
            field=jsonfield.fields.JSONField(blank=True, default=None, help_text='Campaign Plan JSON data. Must conform to the schema defined in CampaignPlan.ts', null=True),
        ),
    ]
