# Generated by Django 2.1.7 on 2019-04-03 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_migrate_rents_to_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='lowest_monthly_rent',
        ),
        migrations.RemoveField(
            model_name='period',
            name='monthly_average_rent',
        ),
    ]
