# Generated by Django 2.1.7 on 2019-04-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_remove_rents_from_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='leases_due_to_expire',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_leases_due_to_expire',
        ),
    ]
