# Generated by Django 2.1.7 on 2019-04-04 20:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import remark.projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0018_remove_leases_due_to_expire'),
    ]

    operations = [
        migrations.CreateModel(
            name='Spreadsheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The creation date for this spreadsheet record.')),
                ('kind', models.CharField(choices=[('periods', 'Periods'), ('modeling', 'Modeling (must provide a subkind, too)'), ('market', 'Market Report'), ('campaign', 'Campaign Plan')], db_index=True, help_text='The kind of data this spreadsheet contains.', max_length=128)),
                ('subkind', models.CharField(blank=True, db_index=True, default='', help_text='The kind of Modeling spreadsheet (if applicable). Run Rate, Schedule Driven, etc', max_length=128)),
                ('file', models.FileField(help_text='The underlying spreadsheet (probably .xlsx) file.', upload_to=remark.projects.models.spreadsheet_media_path)),
                ('imported_data', jsonfield.fields.JSONField(blank=True, default=None, editable=False, help_text='Raw imported JSON data. Schema depends on spreadsheet kind.', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spreadsheets', to='projects.Project')),
                ('uploaded_by', models.ForeignKey(blank=True, default=None, help_text='The user that uploaded this spreadsheet.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddIndex(
            model_name='spreadsheet',
            index=models.Index(fields=['created', 'kind'], name='projects_sp_created_8ef1da_idx'),
        ),
        migrations.AddIndex(
            model_name='spreadsheet',
            index=models.Index(fields=['created', 'kind', 'subkind'], name='projects_sp_created_b30a0a_idx'),
        ),
    ]
