# Generated by Django 2.1.8 on 2019-04-09 13:56

from django.db import migrations, models


def set_true_for_existing_projects(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Project.objects.all().update(
        baseline_report_enabled=True,
        campaign_plan_enabled=True,
        modeling_enabled=True,
        tam_enabled=True,
    )


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_add_total_units_to_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='baseline_report_enabled',
            field=models.BooleanField(default=False, verbose_name='Show Baseline Report?'),
        ),
        migrations.AddField(
            model_name='project',
            name='campaign_plan_enabled',
            field=models.BooleanField(default=False, verbose_name='Show Campaign Plan?'),
        ),
        migrations.AddField(
            model_name='project',
            name='modeling_enabled',
            field=models.BooleanField(default=False, verbose_name='Show Modeling?'),
        ),
        migrations.AddField(
            model_name='project',
            name='tam_enabled',
            field=models.BooleanField(default=False, verbose_name='Show TAM?'),
        ),
        migrations.RunPython(set_true_for_existing_projects, do_nothing)
    ]
