# Generated by Django 2.1.8 on 2019-04-15 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0022_rename_target_lease_percent")]

    operations = [
        migrations.AlterField(
            model_name="spreadsheet",
            name="kind",
            field=models.CharField(
                choices=[
                    ("periods", "Periods"),
                    ("model", "Modeling"),
                    ("market", "Market Report"),
                    ("campaign", "Campaign Plan"),
                ],
                db_index=True,
                help_text="The kind of data this spreadsheet contains.",
                max_length=128,
            ),
        )
    ]
