# Generated by Django 2.1.8 on 2019-04-16 20:39

from django.db import migrations, models
import django.db.models.deletion
import remark.lib.metrics.period


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0024_add_target_occupied_units'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetPeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(db_index=True, help_text='The first date, inclusive, that this target period tracks.')),
                ('end', models.DateField(db_index=True, help_text='The final date, exclusive, that this target period tracks.')),
                ('target_leased_rate', models.DecimalField(blank=True, decimal_places=3, default=None, help_text='Target: lease percentage (like 0.9)', max_digits=4, null=True)),
                ('target_lease_applications', models.IntegerField(blank=True, default=None, help_text='Target: lease applications', null=True)),
                ('target_leases_executed', models.IntegerField(blank=True, default=None, help_text='Target: leases execfuted', null=True)),
                ('target_lease_renewal_notices', models.IntegerField(blank=True, default=None, help_text='Target: lease renewal notices', null=True)),
                ('target_lease_renewals', models.IntegerField(blank=True, default=None, help_text='Target: lease renewals', null=True)),
                ('target_lease_vacation_notices', models.IntegerField(blank=True, default=None, help_text='Target: lease vacation notices', null=True)),
                ('target_lease_cds', models.IntegerField(blank=True, default=None, help_text='Target: lease cancellations and denials', null=True)),
                ('target_delta_leases', models.IntegerField(blank=True, default=None, help_text='Target: delta: leases', null=True)),
                ('target_move_ins', models.IntegerField(blank=True, default=None, help_text='Target: move ins', null=True)),
                ('target_move_outs', models.IntegerField(blank=True, default=None, help_text='Target: move outs', null=True)),
                ('target_occupied_units', models.IntegerField(blank=True, default=None, help_text='Target: occupied units', null=True)),
                ('target_acq_investment', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Target: total acquisition investment', max_digits=10, null=True)),
                ('target_ret_investment', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Target: total retention investment', max_digits=10, null=True)),
                ('target_usvs', models.IntegerField(blank=True, default=None, help_text='Target: USVs', null=True)),
                ('target_inquiries', models.IntegerField(blank=True, default=None, help_text='Target: INQs', null=True)),
                ('target_tours', models.IntegerField(blank=True, default=None, help_text='Target: tours', null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_periods', to='projects.Project')),
            ],
            options={
                'ordering': ['start'],
            },
            bases=(remark.lib.metrics.period.ModelPeriod, models.Model),
        ),
    ]
