# Generated by Django 2.1.8 on 2019-04-16 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0026_move_target_values'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='period',
            name='target_acq_investment',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_delta_leases',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_inquiries',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_lease_applications',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_lease_cds',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_lease_renewal_notices',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_lease_renewals',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_lease_vacation_notices',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_leased_rate',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_leases_executed',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_move_ins',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_move_outs',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_occupied_units',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_ret_investment',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_tours',
        ),
        migrations.RemoveField(
            model_name='period',
            name='target_usvs',
        ),
    ]
