# Generated by Django 2.1.8 on 2019-04-17 05:27

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [("projects", "0027_delete_old_target_fields")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="selected_model_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="The name of the currently selected model, if any.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tmp_campaign_plan_json",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=None,
                help_text="Campaign Plan JSON data. Must conform to the schema defined in CampaignPlan.ts",
                null=True,
                verbose_name="Campaign Data",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tmp_market_report_json",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=None,
                help_text="Total Addressable Market (TAM) report JSON data. Must conform to the schema defined in MarketAnalysis.ts",
                null=True,
                verbose_name="TAM Data",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="tmp_modeling_report_json",
            field=jsonfield.fields.JSONField(
                blank=True,
                default=None,
                help_text="Modeling JSON data. Must conform to the schema defined in ModelingOptions.ts",
                null=True,
                verbose_name="Modeling Data",
            ),
        ),
    ]
