# Generated by Django 2.1.8 on 2019-04-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0027_delete_old_target_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='leased_units_end',
            field=models.IntegerField(default=None, editable=False, help_text='Number of leased units at period end. (Cannot be edited.)', null=True),
        ),
    ]
