# Generated by Django 2.1.8 on 2019-04-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0028_add_leased_units_at_end_to_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='period',
            name='occupied_units_end',
            field=models.IntegerField(default=None, editable=False, help_text='Number of units occupied at period end. (Cannot be edited.)', null=True),
        ),
    ]
