# Generated by Django 2.1.8 on 2019-04-25 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_add_occupied_units_end_to_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google Analytics')], max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projects.Project', related_name="analytics_provider")),
            ],
        ),
    ]
