# Generated by Django 2.2 on 2019-04-29 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0028_add_selected_model_name"),
        ("projects", "0029_add_occupied_units_end_to_period"),
    ]

    operations = []
