# Generated by Django 2.2 on 2019-04-30 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0030_project_address'),
        ('projects', '0030_merge_20190429_1724'),
    ]

    operations = [
    ]
