# Generated by Django 2.1.8 on 2019-04-25 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20190423_1624'),
        ('projects', '0030_analyticsprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='geo.Address'),
        ),
    ]
