# Generated by Django 2.2.1 on 2019-05-09 22:04

from django.db import migrations


def fix_previously_imported_centers(apps, schema_editor):
    # Reverse the ordering of all previously imported center points, since
    # they were incorrectly imported as [latitude, longitude] instead of
    # [longitude, latitude] as required by the GeoJSON RFC.
    Project = apps.get_model("projects", "Project")
    for project in Project.objects.all():
        if project.tmp_market_report_json:
            report = dict(project.tmp_market_report_json)
            estimated_population = report.get("estimated_population", {})
            center = estimated_population.get("center", {})
            coordinates = center.get("coordinates")
            if coordinates is not None:
                report["estimated_population"]["center"]["coordinates"] = [
                    coordinates[1],
                    coordinates[0],
                ]
                project.tmp_market_report_json = report
                project.save()


class Migration(migrations.Migration):

    dependencies = [("projects", "0031_merge_20190430_1933")]

    operations = [migrations.RunPython(fix_previously_imported_centers)]
