# Generated by Django 2.2.1 on 2019-05-09 18:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0031_merge_20190430_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(db_index=True, help_text='The first date, inclusive, that this target period tracks.')),
                ('end', models.DateField(db_index=True, help_text='The final date, exclusive, that this target period tracks.')),
                ('send_datetime', models.DateField()),
                ('lease_rate_text', models.TextField()),
                ('top_performing_kpi', models.TextField(choices=[('lease_rate', 'Lease Rate'), ('retention_rate', 'Retention Rate'), ('occupied_rate', 'Occupied'), ('cds', 'Cancellations and Denials'), ('renew', 'Notices to Renew'), ('vacate', 'Notice to Vacate'), ('move_ins', 'Move Ins'), ('move_outs', 'Move Outs'), ('usv', 'Volume of USV'), ('inq', 'Volume of INQ'), ('tou', 'Volume of TOU'), ('app', 'Volume of APP'), ('exe', 'Volume of EXE'), ('usv_inq', 'USV > INQ'), ('inq_tou', 'INQ > TOU'), ('tou_app', 'TOU > APP'), ('app_exe', 'APP > EXE'), ('usv_exe', 'USV > EXE'), ('cost_per_usv', 'Cost per USV'), ('cost_per_inq', 'Cost per INQ'), ('cost_per_tou', 'Cost per TOU'), ('cost_per_app', 'Cost per APP'), ('cost_per_exe', 'Cost per EXE')])),
                ('top_performing_insight', models.TextField()),
                ('low_performing_kpi', models.TextField(choices=[('lease_rate', 'Lease Rate'), ('retention_rate', 'Retention Rate'), ('occupied_rate', 'Occupied'), ('cds', 'Cancellations and Denials'), ('renew', 'Notices to Renew'), ('vacate', 'Notice to Vacate'), ('move_ins', 'Move Ins'), ('move_outs', 'Move Outs'), ('usv', 'Volume of USV'), ('inq', 'Volume of INQ'), ('tou', 'Volume of TOU'), ('app', 'Volume of APP'), ('exe', 'Volume of EXE'), ('usv_inq', 'USV > INQ'), ('inq_tou', 'INQ > TOU'), ('tou_app', 'TOU > APP'), ('app_exe', 'APP > EXE'), ('usv_exe', 'USV > EXE'), ('cost_per_usv', 'Cost per USV'), ('cost_per_inq', 'Cost per INQ'), ('cost_per_tou', 'Cost per TOU'), ('cost_per_app', 'Cost per APP'), ('cost_per_exe', 'Cost per EXE')])),
                ('low_performing_insight', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, default=None, help_text='The user that created this report.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_emails', to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='PerformanceEmailKPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(choices=[('lease_rate', 'Lease Rate'), ('retention_rate', 'Retention Rate'), ('occupied_rate', 'Occupied'), ('cds', 'Cancellations and Denials'), ('renew', 'Notices to Renew'), ('vacate', 'Notice to Vacate'), ('move_ins', 'Move Ins'), ('move_outs', 'Move Outs'), ('usv', 'Volume of USV'), ('inq', 'Volume of INQ'), ('tou', 'Volume of TOU'), ('app', 'Volume of APP'), ('exe', 'Volume of EXE'), ('usv_inq', 'USV > INQ'), ('inq_tou', 'INQ > TOU'), ('tou_app', 'TOU > APP'), ('app_exe', 'APP > EXE'), ('usv_exe', 'USV > EXE'), ('cost_per_usv', 'Cost per USV'), ('cost_per_inq', 'Cost per INQ'), ('cost_per_tou', 'Cost per TOU'), ('cost_per_app', 'Cost per APP'), ('cost_per_exe', 'Cost per EXE')])),
                ('category', models.TextField(choices=[('top', 'Top'), ('risk', 'Risk'), ('low', 'Low')])),
                ('performance_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='performance_kpis', to='projects.PerformanceEmail')),
            ],
        ),
    ]
