# Generated by Django 2.2 on 2019-04-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0031_project_address'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='analyticsprovider',
            constraint=models.UniqueConstraint(fields=('project', 'provider'), name='unique_project_provider'),
        ),
    ]
