# Generated by Django 2.2 on 2019-05-07 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import remark.projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0031_merge_20190430_1933'),
    ]

    operations = [
        migrations.CreateModel(
            name='TAMExportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The underlying spreadsheet (probably .xlsx) file.', upload_to=remark.projects.models.spreadsheet_media_path)),
                ('exported_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date exported.')),
                ('args_json', jsonfield.fields.JSONField(blank=True, default=None, help_text='The arguments used to build TAM export file.', null=True, verbose_name='TAM Export Arguments')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tam_export_logs', to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tam_export_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
