# Generated by Django 2.2.1 on 2019-05-10 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_tamexportlog'),
        ('projects', '0032_fix_est_pop_center_ordering'),
    ]

    operations = [
    ]
