# Generated by Django 2.2.1 on 2019-05-09 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_fix_est_pop_center_ordering'),
        ('projects', '0032_project_view_group'),
    ]

    operations = [
    ]
