# Generated by Django 2.2 on 2019-05-02 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_project_view_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='competitors',
            field=models.ManyToManyField(related_name='_project_competitors_+', to='projects.Project'),
        ),
    ]
