# Generated by Django 2.2.1 on 2019-05-14 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields
import remark.projects.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('projects', '0032_fix_est_pop_center_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_name',
            field=models.CharField(default='', help_text='The company that hired Remarkaby.', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='email_distribution_list',
            field=models.TextField(default='', help_text='Comma separated list of people to receive email updates about this Project.', max_length=2000),
        ),
        migrations.AddField(
            model_name='project',
            name='email_list_id',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.CreateModel(
            name='TAMExportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='The underlying spreadsheet (probably .xlsx) file.', upload_to=remark.projects.models.tam_export_media_path)),
                ('exported_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='The date exported.')),
                ('args_json', jsonfield.fields.JSONField(blank=True, default=None, help_text='The arguments used to build TAM export file.', null=True, verbose_name='TAM Export Arguments')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tam_export_logs', to='projects.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tam_export_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
