# Generated by Django 2.2.1 on 2019-05-09 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0032_performanceemail_performanceemailkpi'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceemail',
            name='campaign_health',
            field=models.TextField(choices=[('0', 'Requires Review'), ('1', 'At Risk'), ('2', 'On Track')], default='2'),
        ),
        migrations.AddField(
            model_name='performanceemail',
            name='email_campaign_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_name',
            field=models.CharField(default='', help_text='The company that hired Remarkaby.', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='email_distribution_list',
            field=models.TextField(default='', help_text='Comma separated list of people to receive email updates about this Project.', max_length=2000),
        ),
        migrations.AddField(
            model_name='project',
            name='email_list_id',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='performanceemail',
            name='send_datetime',
            field=models.DateField(default=None, null=True),
        ),
    ]
