# Generated by Django 2.2.1 on 2019-05-14 20:03

from django.db import migrations, models
import remark.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_merge_20190510_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='customer_name',
            field=models.CharField(default='', help_text='The company that hired Remarkaby.', max_length=255),
        ),
        migrations.AddField(
            model_name='project',
            name='email_distribution_list',
            field=models.TextField(default='', help_text='Comma separated list of people to receive email updates about this Project.', max_length=2000),
        ),
        migrations.AddField(
            model_name='project',
            name='email_list_id',
            field=models.CharField(default=None, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tamexportlog',
            name='file',
            field=models.FileField(help_text='The underlying spreadsheet (probably .xlsx) file.', upload_to=remark.projects.models.tam_export_media_path),
        ),
    ]
