# Generated by Django 2.2.1 on 2019-05-13 13:34

from django.db import migrations, models
import remark.projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_merge_20190510_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tamexportlog',
            name='file',
            field=models.FileField(help_text='The underlying spreadsheet (probably .xlsx) file.', upload_to=remark.projects.models.tam_export_media_path),
        ),
    ]
