# Generated by Django 2.2.1 on 2019-05-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0033_merge_20190509_2230'),
        ('projects', '0033_merge_20190510_1848'),
    ]

    operations = [
    ]
