# Generated by Django 2.2.1 on 2019-05-28 03:54

from django.db import migrations
import remark.projects.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0036_rename_building_image_to_building_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='building_image',
            field=stdimage.models.StdImageField(blank=True, default='', help_text='Front photo shot of the property.<br/>Resized variants (309x220, 180x180, 76x76) will also be created on Amazon S3.', upload_to=remark.projects.models.building_image_media_path),
        ),
        migrations.AlterField(
            model_name='project',
            name='building_logo',
            field=stdimage.models.StdImageField(blank=True, default='', help_text='Property logo.<br/>Resized variants (180x180, 76x76) will also be created on Amazon S3.', upload_to=remark.projects.models.building_logo_media_path),
        ),
    ]
