# Generated by Django 2.2.1 on 2019-05-28 03:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0037_add_business_and_foud_to_project'),
    ]

    operations = [
        migrations.RenameField('project', 'building_image', 'building_logo'),
    ]
