# Generated by Django 2.2.2 on 2019-06-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0039_add_building_image_for_front'),
        ('projects', '0037_project_competitors'),
    ]

    operations = [
    ]
