# Generated by Django 2.2.2 on 2019-06-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0040_merge_20190612_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='competitors',
            field=models.ManyToManyField(blank=True, to='projects.Project'),
        ),
    ]
