# Generated by Django 2.2.2 on 2019-06-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0042_add_shared_flags_to_project'),
        ('projects', '0035_project_view_group'),
    ]

    operations = [
    ]
