# Generated by Django 2.2.2 on 2019-06-24 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0044_auto_20190624_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='custom_tags',
            field=models.ManyToManyField(blank=True, to='projects.Tag'),
        ),
    ]
