# Generated by Django 2.2.2 on 2019-06-27 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0045_auto_20190624_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='fund',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.Fund'),
        ),
    ]
