# Generated by Django 2.2.2 on 2019-06-18 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0047_copy_modeling_to_new_models'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='spreadsheet',
            name='projects_sp_created_b30a0a_idx',
        ),
        migrations.RemoveField(
            model_name='project',
            name='selected_model_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='tmp_modeling_report_json',
        ),
        migrations.RemoveField(
            model_name='spreadsheet',
            name='subkind',
        ),
    ]
