# Generated by Django 2.2.2 on 2019-07-01 15:59

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0048_remove_old_modeling_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='campaign_id',
            new_name='public_id',
        ),
        migrations.RenameField(
            model_name='campaignmodel',
            old_name='campaign_model_id',
            new_name='public_id',
        ),
        migrations.RenameField(
            model_name='spreadsheet2',
            old_name='spreadsheet_id',
            new_name='public_id',
        ),
        migrations.AlterField(
            model_name='campaign',
            name='selected_campaign_model',
            field=models.ForeignKey(blank=True, help_text='All target values will be replaced by those in the newly selected model.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='projects.CampaignModel', to_field='public_id'),
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_models', to='projects.Campaign', to_field='public_id'),
        ),
        migrations.AlterField(
            model_name='campaignmodel',
            name='spreadsheet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_models', to='projects.Spreadsheet2', to_field='public_id'),
        ),
        migrations.AlterField(
            model_name='spreadsheet2',
            name='json_data',
            field=jsonfield.fields.JSONField(default=None, help_text='Raw imported JSON data. Schema depends on spreadsheet kind.'),
        ),
    ]
