# Generated by Django 2.2.2 on 2019-07-01 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0049_rename_id_fields_to_public_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='selected_campaign_model',
            field=models.ForeignKey(blank=True, help_text='All target values will be replaced by those in the newly selected model.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='projects.CampaignModel'),
        ),
    ]
