# Generated by Django 2.2.3 on 2019-07-02 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0046_auto_20190627_1759'),
        ('projects', '0051_add_campaign_model_to_target_period'),
    ]

    operations = [
    ]
