# Generated by Django 2.2.3 on 2019-07-10 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [("projects", "0052_merge_20190702_1843")]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="asset_manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"business_type": 2},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset_manager",
                to="crm.Business",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="property_manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"business_type": 3},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="property_manager",
                to="crm.Business",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="property_owner",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"business_type": 1},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="property_owner",
                to="crm.Business",
            ),
        ),
    ]
