# Generated by Django 2.2.3 on 2019-07-12 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("projects", "0052_merge_20190702_1843")]

    operations = [migrations.RemoveField(model_name="project", name="customer_name")]
