# Generated by Django 2.2.3 on 2019-07-09 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('projects', '0052_merge_20190702_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='admin_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_of', to='auth.Group'),
        ),
        migrations.AlterField(
            model_name='project',
            name='view_group',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='view_of', to='auth.Group'),
        ),
    ]
