# Generated by Django 2.2.3 on 2019-07-10 10:02

from django.db import migrations


def add_groups(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Group = apps.get_model('auth', 'Group')
    for p in Project.objects.all():
        if p.admin_group is not None:
            continue
        admin_group = Group(name=f"project | {p.name} | admin")
        admin_group.save()
        p.admin_group = admin_group
        p.save()


def remove_groups(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for p in Project.objects.all():
        admin_group = p.admin_group
        if admin_group is not None:
            admin_group.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0053_add_admin_group'),
    ]

    operations = [
        migrations.RunPython(add_groups, remove_groups),
    ]
