# Generated by Django 2.2.3 on 2019-07-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0056_remove_users_from_project")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="property_type",
            field=models.IntegerField(
                choices=[
                    (1, "Multifamily - Standard"),
                    (2, "Multifamily - Micro"),
                    (3, "Student"),
                    (4, "Housing"),
                    (5, "Senior"),
                    (6, "Housing"),
                    (7, "Planned"),
                    (8, "Communities"),
                    (9, "Condominiums"),
                ],
                null=True,
            ),
        )
    ]
