# Generated by Django 2.2.3 on 2019-07-19 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0056_remove_users_from_project'),
        ('projects', '0053_make_business_fields_optional'),
    ]

    operations = [
    ]
