# Generated by Django 2.2.3 on 2019-07-16 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("projects", "0056_remove_users_from_project")]

    operations = [
        migrations.AddField(
            model_name="project",
            name="building_class",
            field=models.IntegerField(
                choices=[(1, "Class A"), (2, "Class B"), (3, "Class C")], default=1
            ),
        )
    ]
