# Generated by Django 2.2.3 on 2019-07-23 09:10

from django.core.management import call_command
from django.db import migrations


def generate_images(apps, schema_editor):
    call_command('rendervariations', 'projects.Project.building_image', ignore_missing=True)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0057_merge_20190719_0759'),
    ]

    operations = [
        migrations.RunPython(generate_images, noop)
    ]
