# Generated by Django 2.2.3 on 2019-07-24 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0005_allow_business_multitype"),
        ("projects", "0057_merge_20190719_0759"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="asset_manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_asset_manager": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asset_manager",
                to="crm.Business",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="property_manager",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_property_manager": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="property_manager",
                to="crm.Business",
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="property_owner",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_property_owner": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="property_owner",
                to="crm.Business",
            ),
        ),
    ]
