# Generated by Django 2.2.3 on 2019-07-24 12:44

from django.db import migrations


data = [
    {
        "full_name": "Pre-Lease",
        "short_name": "pre-lease",
    },
    {
        "full_name": "Lease-Up",
        "short_name": "lease-up",
    },
    {
        "full_name": "Phased Delivery / 2+ Buildings",
        "short_name": "phased delivery",
    },
    {
        "full_name": "Maintain Stabilization",
        "short_name": "stabilization",
    },
    {
        "full_name": "Improve Performance",
        "short_name": "performance",
    },
    {
        "full_name": "Manage Occupancy",
        "short_name": "occupancy",
    },
    {
        "full_name": "Reintroduce Asset",
        "short_name": "asset",
    },
    {
        "full_name": "Dual Strategy / 2+ Buildings",
        "short_name": "dual strategy",
    },
    {
        "full_name": "Other",
        "short_name": "other",
    },
]


def create_lease_stages(apps, schema_editor):
    LeaseStage = apps.get_model('projects', 'LeaseStage')
    for d in data:
        stage = LeaseStage(**d)
        stage.save()


def clear_lease_stages(apps, schema_editor):
    LeaseStage = apps.get_model('projects', 'LeaseStage')
    LeaseStage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_add_lease_stage_models'),
    ]

    operations = [
        migrations.RunPython(create_lease_stages, clear_lease_stages)
    ]
