# Generated by Django 2.2.3 on 2019-07-24 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0006_add_developer_business_type"),
        ("projects", "0058_allow_business_multitype"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="developer",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={"is_developer": True},
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="developer",
                to="crm.Business",
            ),
        )
    ]
