# Generated by Django 2.2.3 on 2019-07-24 12:44

from django.db import migrations


data = []


def create_lease_stages(apps, schema_editor):
    LeaseStage = apps.get_model('projects', 'LeaseStage')
    for d in data:
        stage = LeaseStage(**d)
        stage.save()


def clear_lease_stages(apps, schema_editor):
    LeaseStage = apps.get_model('projects', 'LeaseStage')
    LeaseStage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_add_lease_stage_models'),
    ]

    operations = [
        migrations.RunPython(create_lease_stages, clear_lease_stages)
    ]
