# Generated by Django 2.2.3 on 2019-07-11 11:55

from django.db import migrations


def create_temporary_address(apps):
    Address = apps.get_model('geo', 'Address')
    temp_address = Address(
        formatted_address="Columbia Tower",
        street_address_1="111 Columbia Street",
        street_address_2="",
        city="Seattle",
        state="WA",
        zip_code="98111",
        country="USA",
        geocode_json=None,
    )
    temp_address.save()
    return temp_address


def create_properties(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    Property = apps.get_model('projects', 'Property')
    for p in Project.objects.all():
        if p.property is not None:
            continue
        address = p.address
        if not address:
            address = create_temporary_address(apps)
        property = Property(
            name=f'{p.name}',
            average_tenant_age=p.average_tenant_age or 0,
            total_units=p.total_units or 0,
            highest_monthly_rent=p.highest_monthly_rent or 0,
            average_monthly_rent=p.average_monthly_rent or 0,
            lowest_monthly_rent=p.lowest_monthly_rent or 0,
            geo_address=address,
            building_logo=p.building_logo,
            building_image=p.building_image,
        )
        property.save()
        p.property = property
        p.save()


def remove_properties(apps, schema_editor):
    Project = apps.get_model('projects', 'Project')
    for p in Project.objects.all():
        if not p.property:
            continue
        property = p.property
        # Fill project properties from Property values
        p.average_tenant_age = property.average_tenant_age
        p.total_units = property.total_units
        p.highest_monthly_rent = property.highest_monthly_rent
        p.average_monthly_rent = property.average_monthly_rent
        p.lowest_monthly_rent = property.lowest_monthly_rent
        p.address = property.geo_address
        p.building_logo = property.building_logo
        p.building_image = property.building_image

        p.save()
        property.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_add_property_model'),
    ]

    operations = [
        migrations.RunPython(create_properties, remove_properties),
    ]
