# Generated by Django 2.2.3 on 2019-07-24 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_fill_lease_stages'),
    ]

    operations = [
    ]
