# Generated by Django 2.2.3 on 2019-07-24 12:56

from django.db import migrations


def add_lease_stage_to_project(apps, schema_editor):
    LeaseStage = apps.get_model('projects', 'LeaseStage')
    PropertyLeaseStage = apps.get_model('projects', 'PropertyLeaseStage')
    Project = apps.get_model('projects', 'Project')
    stage = LeaseStage.objects.get(short_name="stabilization")

    for p in Project.objects.all():
        pass


def remove_lease_stage_from_project(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0059_fill_lease_stages'),
    ]

    operations = [
        migrations.RunPython(add_lease_stage_to_project, remove_lease_stage_from_project)
    ]
