# Generated by Django 2.2.3 on 2019-07-25 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_add_building_class_to_project'),
        ('projects', '0058_add_property_type'),
        ('projects', '0059_add_developer_business_type'),
    ]

    operations = [
    ]
