# Generated by Django 2.2.3 on 2019-07-25 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0060_remove_properties_from_project'),
        ('projects', '0060_merge_20190725_2109'),
    ]

    operations = [
    ]
