# Generated by Django 2.2.3 on 2019-07-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0061_merge_20190725_2306'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='building_class',
        ),
        migrations.RemoveField(
            model_name='project',
            name='property_type',
        ),
        migrations.AddField(
            model_name='property',
            name='building_class',
            field=models.IntegerField(choices=[(1, 'Class A'), (2, 'Class B'), (3, 'Class C')], default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.IntegerField(choices=[(1, 'Multifamily - Standard'), (2, 'Multifamily - Micro'), (3, 'Student Housing'), (4, 'Senior Housing'), (5, 'Planned Communities'), (6, 'Condominiums')], null=True),
        ),
    ]
