# Generated by Django 2.2.3 on 2019-07-25 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0058_add_include_in_remarkably_averages_to_project'),
        ('projects', '0062_auto_20190725_2306'),
    ]

    operations = [
    ]
