# Generated by Django 2.2.3 on 2019-07-24 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_merge_20190725_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PropertyLeaseStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(db_index=True)),
                ('end', models.DateField(blank=True, db_index=True, null=True)),
                ('includes_remarkably_effect', models.BooleanField(blank=True, default=True)),
                ('lease_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.LeaseStage')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
