# Generated by Django 2.2.3 on 2019-07-31 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_merge_20190725_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetperiod',
            name='target_leases_executed',
            field=models.IntegerField(blank=True, default=None, help_text='Target: leases executed', null=True),
        ),
    ]
