# Generated by Django 2.2.3 on 2019-07-29 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0063_merge_20190725_2324'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaseStage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=30)),
                ('short_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='period',
            name='includes_remarkably_effect',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AddField(
            model_name='period',
            name='lease_stage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.LeaseStage'),
        ),
    ]
