# Generated by Django 2.2.3 on 2019-08-01 11:11

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0064_auto_20190731_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='building_image_cropping',
            field=image_cropping.fields.ImageRatioField('building_image', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='building image cropping'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_image_landscape_cropping',
            field=image_cropping.fields.ImageRatioField('building_image', '309x220', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='building image landscape cropping'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_logo_cropping',
            field=image_cropping.fields.ImageRatioField('building_logo', '180x180', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='building logo cropping'),
        ),
    ]
