# Generated by Django 2.2.3 on 2019-07-24 12:56

from django.db import migrations, models


def add_lease_stage_to_period(apps, schema_editor):
    LeaseStage = apps.get_model('projects', 'LeaseStage')
    Period = apps.get_model('projects', 'Period')

    stage = LeaseStage.objects.get(short_name="stabilization")
    for p in Period.objects.all():
        p.lease_stage = stage
        p.save()


def remove_lease_stage_from_project(apps, schema_editor):
    LeaseStage = apps.get_model('projects', 'LeaseStage')
    Period = apps.get_model('projects', 'Period')

    stage = LeaseStage.objects.get(short_name="stabilization")
    for p in Period.objects.filter(lease_stage=stage):
        p.lease_stage = None
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_fill_lease_stages'),
    ]

    operations = [
        migrations.RunPython(add_lease_stage_to_period, remove_lease_stage_from_project)
    ]
