# Generated by Django 2.2.3 on 2019-08-08 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0065_add_building'),
        ('projects', '0065_remove_poylgon_from_tam_json'),
    ]

    operations = [
    ]
