# Generated by Django 2.2.3 on 2019-07-24 12:56

from django.db import migrations, models


def get_leased_units(period):
    """
    Got calculation from `ComputedPeriod.leased_units`
    """
    underlying_value = period.leased_units_end
    if underlying_value is not None:
        result = underlying_value
    else:
        delta_leases = period.leases_executed - period.leases_ended
        leased_units_start = period.leased_units_start or 0
        result = leased_units_start + delta_leases
    return result


def get_leased_rate(period):
    total_units = period.project.property.total_units
    if not total_units:
        return 0
    leased_units = get_leased_units(period)
    return leased_units / total_units


def add_lease_stage_to_period(apps, schema_editor):
    LeaseStage = apps.get_model('projects', 'LeaseStage')
    Period = apps.get_model('projects', 'Period')

    stabilization = LeaseStage.objects.get(short_name='stabilization')
    performance = LeaseStage.objects.get(short_name='performance')
    for p in Period.objects.filter(lease_stage__isnull=True):
        leased_rate = get_leased_rate(p)
        if leased_rate >= 0.85:
            stage = stabilization
        else:
            stage = performance
        p.lease_stage = stage
        p.save()


def remove_lease_stage_from_project(apps, schema_editor):
    LeaseStage = apps.get_model('projects', 'LeaseStage')
    Period = apps.get_model('projects', 'Period')

    stabilization = LeaseStage.objects.get(short_name='stabilization')
    performance = LeaseStage.objects.get(short_name='performance')
    for p in Period.objects.filter(lease_stage__in=[performance, stabilization]):
        leased_rate = get_leased_rate(p)
        if leased_rate >= 0.85 and p.lease_stage.short_name == 'stabilization':
            p.lease_stage = None
        elif leased_rate < 0.85 and p.lease_stage.short_name == 'performance':
            p.lease_stage = None
        p.save()


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0066_fill_lease_stages'),
    ]

    operations = [
        migrations.RunPython(add_lease_stage_to_period, remove_lease_stage_from_project)
    ]
