# Generated by Django 2.2.3 on 2019-08-09 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0068_make_lease_stage_not_nullable'),
        ('projects', '0066_merge_20190808_2351'),
    ]

    operations = [
    ]
