# Generated by Django 2.2.4 on 2019-08-09 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0069_merge_20190809_0025'),
        ('projects', '0065_add_image_cropping_fields'),
    ]

    operations = [
    ]
