# Generated by Django 2.2.4 on 2019-08-12 06:42

from django.db import migrations, models
import remark.projects.models


class Migration(migrations.Migration):

    dependencies = [("projects", "0070_merge_20190809_0106")]

    operations = [
        migrations.AlterField(
            model_name="building",
            name="public_id",
            field=models.CharField(
                default=remark.projects.models.building_public_id,
                editable=False,
                max_length=50,
                primary_key=True,
                serialize=False,
            ),
        )
    ]
