# Generated by Django 2.2.4 on 2019-09-10 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0005_add_default_listserv_email'),
        ('projects', '0071_fix_field_length_for_building_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='listserv_email',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='email_app.ListservEmail'),
        ),
    ]
