# Generated by Django 2.2.5 on 2019-09-18 20:02

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0071_fix_field_length_for_building_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='building_image_cropping',
            field=image_cropping.fields.ImageRatioField('building_image', '180x180', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='building image cropping'),
        ),
    ]
