# Generated by Django 2.2.5 on 2019-11-05 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20190919_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.IntegerField(choices=[(1, 'Multifamily - Standard'), (2, 'Multifamily - Micro'), (3, 'Student Housing'), (4, 'Senior Housing'), (5, 'Planned Communities'), (6, 'Condominiums'), (7, 'Active Adult')], null=True),
        ),
    ]
