# Generated by Django 2.2.5 on 2019-11-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20190919_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_style',
            field=models.CharField(blank=True, choices=[('low-rise', 'Low-Rise'), ('walk-up', 'Walk-Up'), ('mid-rise', 'Mid-Rise'), ('hi-rise', 'Hi-Rise'), ('tower-block', 'Tower-Block'), ('garden', 'Garden')], max_length=20, null=True),
        ),
    ]
