# Generated by Django 2.2.5 on 2019-09-19 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20190919_2041'),
        ('projects', '0073_set_default_listserv_email'),
    ]

    operations = [
    ]
