# Generated by Django 2.2.7 on 2019-11-07 13:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0073_auto_20191105_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='year_renovated',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Four number digit YYYY', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]