# Generated by Django 2.2.5 on 2019-11-08 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0074_property_year_renovated'),
        ('projects', '0074_property_property_url'),
    ]

    operations = [
    ]
