# Generated by Django 2.2.5 on 2019-11-08 09:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0075_merge_20191108_0737'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, help_text='YYYY (four number digit)', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterField(
            model_name='property',
            name='year_renovated',
            field=models.PositiveSmallIntegerField(blank=True, help_text='YYYY (four number digit)', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)]),
        ),
    ]
