# Generated by Django 2.2.7 on 2019-12-11 20:39

from django.db import migrations, models
import remark.projects.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0076_auto_20191108_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_style',
            field=models.IntegerField(choices=[(0, 'Auto'), (1, 'Low-Rise'), (2, 'Walk-Up'), (3, 'Mid-Rise'), (4, 'Hi-Rise'), (5, 'Tower-Block'), (6, 'Garden'), (7, 'Other')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='property',
            name='building_image',
            field=stdimage.models.StdImageField(blank=True, default='', help_text='Image of property building<br/>Resized variants (605x370, 309x220, 180x180, 76x76) will also be created on Amazon S3.', upload_to=remark.projects.models.building_image_media_path),
        ),
    ]
