# Generated by Django 2.2.8 on 2019-12-12 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0077_add_country_benchmark_model'),
        ('projects', '0077_auto_20191211_2039'),
    ]

    operations = [
    ]
