# Generated by Django 2.2.8 on 2020-01-07 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0078_merge_20191212_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='custom_tags',
            field=models.ManyToManyField(blank=True, related_name='projects', to='projects.Tag'),
        ),
    ]
