# Generated by Django 2.2.9 on 2020-01-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0079_auto_20200107_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='reporting_day',
            field=models.CharField(choices=[('Monday', 'M'), ('Tuesday', 'T'), ('Wednesday', 'W'), ('Thursday', 'Th'), ('Friday', 'F'), ('Saturday', 'Sa'), ('Sunday', 'Su')], default='Monday', max_length=9),
        ),
    ]
