# Generated by Django 2.2.9 on 2020-02-10 21:19

from django.db import migrations

def set_reporting_day(apps, schema_editor):
    Project = apps.get_model("projects", "Project")
    Period = apps.get_model("projects", "Period")
    project_list = Project.objects.all()
    for project in project_list:
        period_list = Period.objects.filter(project_id=project.pk)
        if period_list:
            period = period_list.order_by("start").last()
            period_start = period.start.strftime('%A')
            project.reporting_day = period_start
            project.save(update_fields=['reporting_day'])



class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_project_reporting_day'),
    ]

    operations = [
        migrations.RunPython(set_reporting_day),
    ]
