# Generated by Django 2.2.9 on 2020-02-10 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0080_project_reporting_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reporting_day',
            field=models.CharField(blank=True, choices=[('Monday', 'M'), ('Tuesday', 'T'), ('Wednesday', 'W'), ('Thursday', 'Th'), ('Friday', 'F'), ('Saturday', 'Sa'), ('Sunday', 'Su')], max_length=9, null=True, default="Monday"),
        ),
    ]
