# Generated by Django 2.2.9 on 2020-02-10 20:54

from django.db import migrations

def gen_reporting_day(apps, schema_editor):
    Projects = apps.get_model('projects', 'Project')
    Periods = apps.get_model('projects', 'Period')
    weekDays = ("Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday")
    for project in Projects.objects.all():
        try:
            period = Periods.objects.filter(project_id=project.pk).latest('end')
            reporting_day_index = period.start.weekday()
            project.reporting_day = weekDays[reporting_day_index]
            project.save()
        except:
            print(f"No period data available for project {project.pk}")

class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0081_update_project_reporting_day'),
    ]

    operations = [
        migrations.RunPython(gen_reporting_day)
    ]
