# Generated by Django 2.2.9 on 2020-02-10 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0082_populate_reporting_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='reporting_day',
            field=models.CharField(blank=True, max_length=9, null=True),
        ),
    ]
