# Generated by Django 2.2.10 on 2020-02-27 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0087_make_campaign_baseline_not_nullable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='baseline_end',
        ),
        migrations.RemoveField(
            model_name='project',
            name='baseline_start',
        ),
    ]
