# Generated by Django 2.2.11 on 2020-03-05 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_remove_baseline_from_projects'),
        ('projects', '0085_auto_20200302_2057'),
    ]

    operations = [
    ]
