# Generated by Django 2.2.10 on 2020-03-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0088_remove_baseline_from_projects'),
        ('projects', '0085_auto_20200302_2057'),
    ]

    operations = [
    ]
