# Generated by Django 2.2.11 on 2020-03-05 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0089_merge_20200305_2029'),
        ('projects', '0089_merge_20200305_0211'),
    ]

    operations = [
    ]
