# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  aws-cli: circleci/aws-cli@0.1.1
  node: circleci/node@1.1.3
  heroku: circleci/heroku@0.0.8

jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-node
      - image: circleci/postgres:latest
      - image: circleci/redis:latest
      # pre-built images https://circleci.com/docs/2.0/circleci-images/

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: yarn install --silent
      - run: pipenv --bare install
      - run: yarn build --silent
      - run: pipenv run python manage.py collectstatic
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: mv .env-example .env

      # run tests!
      - run: yarn test-ui
      - run: pipenv run python manage.py test
      - run: pipenv run python manage.py migrate
      - run: pipenv run python manage.py loaddata data/dumped/latest.json

  deploy-staging:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.4

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout
      - aws-cli/install
      - run:
          name: Fetch .env from s3
          command: |
            aws s3 cp s3://remarkably-staging-58d2d32d-caeb-4629-a941-3b16bb028421/env ~/repo/.env
      - run:
          name: Deploy Staging to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/remarkably-staging.git master --force
      - run: curl https://cli-assets.heroku.com/install.sh | sh
      - run: heroku pg:reset --app remarkably-staging DATABASE_URL --confirm remarkably-staging
      - run: heroku run -x -a remarkably-staging python manage.py migrate
      - run: heroku run -x -a remarkably-staging python manage.py loaddata data/dumped/latest.json

  deploy-production:
    docker:
      - image: circleci/python:3.6.4

    working_directory: ~/repo

    steps:
      - run: curl https://cli-assets.heroku.com/install.sh | sh
      - checkout
      - run:
          name: Deploy Master to Heroku Production
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/remarkably.git master --force
      - run: heroku run -x -a remarkably python manage.py migrate

workflows:
  version: 2.1

  tests-only:
    jobs:
      - build:
          filters:
            branches:
              ignore: staging

  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only: staging
      - deploy-staging:
          context: stage-aws
          requires:
            - build
          filters:
            branches:
              only: staging
  
  build-production:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - hold:
        type: approval
        requires:
          - build
      - deploy-production:
          context: deploy-production
          requires:
            - hold
