# Generated by Django 2.2 on 2019-04-29 18:57

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0029_add_occupied_units_end_to_period'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google Analytics')], max_length=255)),
                ('identifier', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_providers', to='projects.Project')),
            ],
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddConstraint(
            model_name='analyticsprovider',
            constraint=models.UniqueConstraint(fields=('project', 'provider'), name='unique_project_provider'),
        ),
    ]
