# Generated by Django 2.2.9 on 2020-01-23 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='analyticsprovider',
            managers=[
            ],
        ),
    ]
