# Generated by Django 2.2.8 on 2019-12-18 16:41

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0078_merge_20191212_2246'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsUniqueSiteVisitors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The date for the USV data.')),
                ('usv_day_count', models.PositiveIntegerField(help_text="The number of sessions marked as a user's first sessions by the day.")),
                ('usv_hourly_count', django.contrib.postgres.fields.ArrayField(base_field=models.PositiveIntegerField(help_text="The number of sessions marked as a user's first sessions by the hour within a the day."), size=24)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, help_text='The date for the data results.')),
                ('project_id', models.ForeignKey(help_text='Project associated with the response', on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
        migrations.CreateModel(
            name='AnalyticsReferralSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_name', models.CharField(help_text='The source of referrals.', max_length=255)),
                ('bounces', models.PositiveIntegerField(help_text='The total number of single page (or single interaction hit) sessions for the property.')),
                ('session_duration', models.CharField(help_text='The length (returned as a string) of a session measured in seconds and reported in second increments.', max_length=255)),
                ('response_id', models.ForeignKey(help_text='analytics response associated with the referral source', on_delete=django.db.models.deletion.CASCADE, to='analytics.AnalyticsResponse')),
            ],
        ),
    ]
