# Generated by Django 2.2.8 on 2020-01-15 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [("analytics", "0001_initial")]

    operations = [migrations.AlterModelManagers(name="analyticsprovider", managers=[])]
