# Generated by Django 2.2.9 on 2020-01-24 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_update_manager'),
        ('analytics', '0002_analyticsreferralsource_analyticsresponse_analyticsuniquesitevisitors'),
    ]

    operations = [
    ]
