# Generated by Django 2.2.9 on 2020-01-30 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_auto_20200123_1926'),
        ('analytics', '0003_merge_20200124_1324'),
    ]

    operations = [
    ]
