# Generated by Django 2.2.1 on 2019-06-17 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import remark.sales.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0012_add_has_population_to_zipcode'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInquiry',
            fields=[
                ('product_inquiry_id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('accelerate', 'Accelerate'), ('optimize', 'Optimize'), ('ground', 'Ground Up'), ('other', 'Not Sure')], max_length=10)),
                ('building_photo', models.ImageField(blank=True, null=True, upload_to=remark.sales.models.building_photo_path)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geo.Address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
