# Generated by Django 2.2.3 on 2019-07-09 17:50

import datetime
from django.db import migrations, models
from django.utils import timezone

def utcnow():
    return datetime.datetime.now(timezone.utc)

class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_add_created_to_product_inquiry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinquiry',
            name='created',
            field=models.DateTimeField(blank=True, default=utcnow),
        ),
    ]
