# Generated by Django 2.2.3 on 2019-08-01 11:12

from django.db import migrations
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20190709_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='productinquiry',
            name='building_photo_cropping',
            field=image_cropping.fields.ImageRatioField('building_photo', '400x400', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text=None, hide_image_field=False, size_warning=True, verbose_name='building photo cropping'),
        ),
    ]
