# Generated by Django 2.2.6 on 2019-11-06 21:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_add_building_photo_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinquiry',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime.utcnow),
        ),
    ]
