# Generated by Django 2.2.3 on 2019-07-10 19:12

from decimal import Decimal
from django.db import migrations, models
import remark.lib.metrics.period


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemarkablyPortfolioAveragePeriod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateField(db_index=True, help_text='The first date, inclusive, that this period tracks.')),
                ('end', models.DateField(db_index=True, help_text='The final date, exclusive, that this period tracks.')),
                ('leased_units_start', models.IntegerField(help_text='Number of leased units at period start.')),
                ('leased_units_end', models.IntegerField(default=None, editable=False, help_text='Number of leased units at period end. (Cannot be edited.)', null=True)),
                ('leases_ended', models.IntegerField(default=0, help_text='Number of leases ended (roughly: move outs)')),
                ('lease_applications', models.IntegerField(default=0, help_text='Number of lease applications')),
                ('leases_executed', models.IntegerField(default=0, help_text='Number of new leases executed')),
                ('lease_cds', models.IntegerField(default=0, help_text='Number of lease cancellations and denials')),
                ('lease_renewal_notices', models.IntegerField(default=0, help_text='Number of lease renewals signed')),
                ('lease_renewals', models.IntegerField(default=0, help_text='Number of lease renewals that took effect')),
                ('lease_vacation_notices', models.IntegerField(default=0, help_text='Number of notices to vacate leases')),
                ('occupiable_units_start', models.IntegerField(blank=True, default=None, help_text='Number of units that can possibly be at period start. If not specified, will be pulled from a previous period.', null=True)),
                ('occupied_units_start', models.IntegerField(help_text='Number of units occupied at period start.')),
                ('occupied_units_end', models.IntegerField(default=None, editable=False, help_text='Number of units occupied at period end. (Cannot be edited.)', null=True)),
                ('move_ins', models.IntegerField(default=0, help_text='Number of units moved into')),
                ('move_outs', models.IntegerField(default=0, help_text='Number of units moved out of')),
                ('acq_reputation_building', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in acquisition reputation building', max_digits=10)),
                ('acq_demand_creation', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in acquisition demand creation', max_digits=10)),
                ('acq_leasing_enablement', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in acquisition leasing enablement', max_digits=10)),
                ('acq_market_intelligence', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in acquisition market intelligence', max_digits=10)),
                ('ret_reputation_building', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in retention reputation building', max_digits=10)),
                ('ret_demand_creation', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in retention demand creation', max_digits=10)),
                ('ret_leasing_enablement', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in retention leasing enablement', max_digits=10)),
                ('ret_market_intelligence', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Amount invested in retention market intelligence', max_digits=10)),
                ('usvs', models.IntegerField(default=0, help_text='The number of unique site visitors during this period.')),
                ('inquiries', models.IntegerField(default=0, help_text='The number of site inquiries during this period.')),
                ('tours', models.IntegerField(default=0, help_text='The number of tours during this period.')),
                ('target_leased_rate', models.DecimalField(blank=True, decimal_places=3, default=None, help_text='Target: lease percentage (like 0.9)', max_digits=4, null=True)),
                ('target_lease_applications', models.IntegerField(blank=True, default=None, help_text='Target: lease applications', null=True)),
                ('target_leases_executed', models.IntegerField(blank=True, default=None, help_text='Target: leases execfuted', null=True)),
                ('target_lease_renewal_notices', models.IntegerField(blank=True, default=None, help_text='Target: lease renewal notices', null=True)),
                ('target_lease_renewals', models.IntegerField(blank=True, default=None, help_text='Target: lease renewals', null=True)),
                ('target_lease_vacation_notices', models.IntegerField(blank=True, default=None, help_text='Target: lease vacation notices', null=True)),
                ('target_lease_cds', models.IntegerField(blank=True, default=None, help_text='Target: lease cancellations and denials', null=True)),
                ('target_delta_leases', models.IntegerField(blank=True, default=None, help_text='Target: delta: leases', null=True)),
                ('target_move_ins', models.IntegerField(blank=True, default=None, help_text='Target: move ins', null=True)),
                ('target_move_outs', models.IntegerField(blank=True, default=None, help_text='Target: move outs', null=True)),
                ('target_occupied_units', models.IntegerField(blank=True, default=None, help_text='Target: occupied units', null=True)),
                ('target_acq_investment', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Target: total acquisition investment', max_digits=10, null=True)),
                ('target_ret_investment', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Target: total retention investment', max_digits=10, null=True)),
                ('target_usvs', models.IntegerField(blank=True, default=None, help_text='Target: USVs', null=True)),
                ('target_inquiries', models.IntegerField(blank=True, default=None, help_text='Target: INQs', null=True)),
                ('target_tours', models.IntegerField(blank=True, default=None, help_text='Target: tours', null=True)),
            ],
            options={
                'ordering': ['start'],
            },
            bases=(remark.lib.metrics.period.ModelPeriod, models.Model),
        ),
    ]
