# Generated by Django 2.2.3 on 2019-07-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='remarkablyportfolioaverageperiod',
            name='average_monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Average rent tenants pay monthly. Applies for the duration of the project.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='remarkablyportfolioaverageperiod',
            name='highest_monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Highest rent tenants pay monthly. Applies for the duration of the project.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='remarkablyportfolioaverageperiod',
            name='lowest_monthly_rent',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Lowest rent tenants pay monthly. Applies for the duration of the project.', max_digits=10, null=True),
        ),
    ]
