# Generated by Django 2.2.3 on 2019-07-19 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='performanceemail',
            name='low_kpi_insight_text',
            field=models.TextField(help_text="Optional text below Off Track KPI's", null=True),
        ),
        migrations.AddField(
            model_name='performanceemail',
            name='risk_kpi_insight_text',
            field=models.TextField(help_text="Optional text below At Risk KPI's", null=True),
        ),
        migrations.AlterField(
            model_name='performanceemail',
            name='low_performing_kpi',
            field=models.TextField(choices=[('lease_rate', 'Leased Rate'), ('retention_rate', 'Retained Rate'), ('occupied_rate', 'Occupancy Rate'), ('cds', 'Cancellations and Denials'), ('renew', 'Number of Notices to Renew'), ('vacate', 'Number of Notices to Vacate'), ('move_ins', 'Move Ins'), ('move_outs', 'Move Outs'), ('usv', 'Number of Unique Site Visitors'), ('inq', 'Number of Inquiries'), ('tou', 'Number of Tours'), ('app', 'Number of Lease Applications'), ('exe', 'Number of Lease Executions'), ('usv_inq', 'Unique Site Visitors > Inquiries'), ('inq_tou', 'Inquiries > Tours'), ('tou_app', 'Tours > Lease Applications'), ('app_exe', 'Lease Applications > Lease Executions'), ('usv_exe', 'Unique Site Visitors > Lease Executions'), ('cost_per_usv', 'Cost per Unique Site Visitor'), ('cost_per_inq', 'Cost per Inquiry'), ('cost_per_tou', 'Cost per Tour'), ('cost_per_app', 'Cost per Lease Application'), ('cost_per_exe', 'Cost per Lease Execution')]),
        ),
        migrations.AlterField(
            model_name='performanceemail',
            name='top_performing_kpi',
            field=models.TextField(choices=[('lease_rate', 'Leased Rate'), ('retention_rate', 'Retained Rate'), ('occupied_rate', 'Occupancy Rate'), ('cds', 'Cancellations and Denials'), ('renew', 'Number of Notices to Renew'), ('vacate', 'Number of Notices to Vacate'), ('move_ins', 'Move Ins'), ('move_outs', 'Move Outs'), ('usv', 'Number of Unique Site Visitors'), ('inq', 'Number of Inquiries'), ('tou', 'Number of Tours'), ('app', 'Number of Lease Applications'), ('exe', 'Number of Lease Executions'), ('usv_inq', 'Unique Site Visitors > Inquiries'), ('inq_tou', 'Inquiries > Tours'), ('tou_app', 'Tours > Lease Applications'), ('app_exe', 'Lease Applications > Lease Executions'), ('usv_exe', 'Unique Site Visitors > Lease Executions'), ('cost_per_usv', 'Cost per Unique Site Visitor'), ('cost_per_inq', 'Cost per Inquiry'), ('cost_per_tou', 'Cost per Tour'), ('cost_per_app', 'Cost per Lease Application'), ('cost_per_exe', 'Cost per Lease Execution')]),
        ),
        migrations.AlterField(
            model_name='performanceemailkpi',
            name='name',
            field=models.TextField(choices=[('lease_rate', 'Leased Rate'), ('retention_rate', 'Retained Rate'), ('occupied_rate', 'Occupancy Rate'), ('cds', 'Cancellations and Denials'), ('renew', 'Number of Notices to Renew'), ('vacate', 'Number of Notices to Vacate'), ('move_ins', 'Move Ins'), ('move_outs', 'Move Outs'), ('usv', 'Number of Unique Site Visitors'), ('inq', 'Number of Inquiries'), ('tou', 'Number of Tours'), ('app', 'Number of Lease Applications'), ('exe', 'Number of Lease Executions'), ('usv_inq', 'Unique Site Visitors > Inquiries'), ('inq_tou', 'Inquiries > Tours'), ('tou_app', 'Tours > Lease Applications'), ('app_exe', 'Lease Applications > Lease Executions'), ('usv_exe', 'Unique Site Visitors > Lease Executions'), ('cost_per_usv', 'Cost per Unique Site Visitor'), ('cost_per_inq', 'Cost per Inquiry'), ('cost_per_tou', 'Cost per Tour'), ('cost_per_app', 'Cost per Lease Application'), ('cost_per_exe', 'Cost per Lease Execution')]),
        ),
    ]
