# Generated by Django 2.2.4 on 2019-08-15 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_optional_texts_to_perf_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceemail',
            name='lease_rate_text',
            field=models.TextField(blank=True, help_text='Optional text for Lease Rate section', null=True),
        ),
        migrations.AlterField(
            model_name='performanceemail',
            name='low_kpi_insight_text',
            field=models.TextField(blank=True, help_text="Optional text for Off Track KPI's", null=True),
        ),
        migrations.AlterField(
            model_name='performanceemail',
            name='low_performing_insight',
            field=models.TextField(blank=True, help_text='Optional text for Lowest Performer', null=True),
        ),
        migrations.AlterField(
            model_name='performanceemail',
            name='risk_kpi_insight_text',
            field=models.TextField(blank=True, help_text="Optional text for At Risk KPI's", null=True),
        ),
        migrations.AlterField(
            model_name='performanceemail',
            name='top_performing_insight',
            field=models.TextField(blank=True, help_text='Optional text for Highest Performer', null=True),
        ),
    ]
