# Generated by Django 2.2.4 on 2019-09-10 00:00

from django.db import migrations, models
import remark.lib.fields


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0003_perf_email_insight_texts_all_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListservEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', remark.lib.fields.NormalizedEmailField(max_length=254, unique=True)),
            ],
        ),
    ]
