# Generated by Django 2.2.7 on 2019-11-22 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0003_perf_email_insight_texts_all_optional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performanceemail',
            name='email_campaign_id',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
