# Generated by Django 2.2.9 on 2020-01-30 21:35

from django.db import migrations

def get_lease_rate_text(apps, schema_editor):
    PerformanceEmails = apps.get_model('email_app', 'PerformanceEmail')
    for row in PerformanceEmails.objects.all():
        row.top_macro_insight_1 = row.lease_rate_text
        row.save()

class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0005_add_macro_insights_fields'),
    ]

    operations = [
        migrations.RunPython(get_lease_rate_text)
    ]
