# Generated by Django 2.2.9 on 2020-01-30 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0006_set_lease_rate_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='performanceemail',
            name='lease_rate_text',
        ),
    ]
