# Generated by Django 2.2.9 on 2020-02-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0007_remove_performanceemail_lease_rate_text'),
    ]

    operations = [
        migrations.CreateModel(
            name='MacroInsights',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(choices=[('lease_rate_against_target', 'lease_rate_against_target'), ('change_health_status', 'change_health_status'), ('usv_exe_off_track', 'usv_exe_off_track'), ('usv_exe_at_risk', 'usv_exe_at_risk'), ('usv_exe_on_track', 'usv_exe_on_track'), ('retention_rate_health', 'retention_rate_health'), ('top_usv_referral', 'top_usv_referral')])),
                ('is_active', models.BooleanField(default=True)),
                ('macro_insight_priority_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['macro_insight_priority_order'],
            },
        ),
    ]
