# Generated by Django 2.1.8 on 2019-04-24 17:00

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address_1', models.CharField(help_text='Street address 1', max_length=255)),
                ('street_address_2', models.CharField(blank=True, help_text='Street address 2', max_length=255, null=True)),
                ('city', models.CharField(max_length=128)),
                ('state', models.CharField(help_text='State / Province', max_length=128)),
                ('zip_code', models.CharField(blank=True, help_text='Zipcode', max_length=32)),
                ('country', models.CharField(max_length=128)),
                ('geo_code_json', jsonfield.fields.JSONField(help_text='Google Geo Code JSON')),
            ],
        ),
    ]
