# Generated by Django 2.1.8 on 2019-04-25 23:44

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_auto_20190423_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='geo_code_json',
        ),
        migrations.AddField(
            model_name='address',
            name='geocode_json',
            field=jsonfield.fields.JSONField(blank=True, default=None, help_text='Raw JSON response from google geocode'),
        ),
    ]
