# Generated by Django 2.1.8 on 2019-04-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("geo", "0004_clean_up_address")]

    operations = [
        migrations.AddField(
            model_name="address",
            name="formatted_address",
            field=models.CharField(
                blank=True,
                help_text="The address in canonical formatted form",
                max_length=255,
            ),
        )
    ]
