# Generated by Django 2.1.8 on 2019-04-29 16:33

from django.db import migrations


def migrate_formatted_addresses(apps, schema_editor):
    from remark.geo.geocode import GeocodeResult

    Address = apps.get_model("geo", "Address")
    for address in Address.objects.all():
        # Don't depend on the presence of the geocode_result property.
        try:
            geocode_result = GeocodeResult(address.geocode_json)
        except Exception:
            geocode_result = None
        if geocode_result:
            address.formatted_address = geocode_result.formatted_address
            address.save()


class Migration(migrations.Migration):

    dependencies = [("geo", "0005_add_formatted_address_to_address")]

    operations = [migrations.RunPython(migrate_formatted_addresses)]
