# Generated by Django 2.1.8 on 2019-04-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("geo", "0006_migrate_formatted_addresses")]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="formatted_address",
            field=models.CharField(
                help_text="The address in canonical formatted form", max_length=255
            ),
        )
    ]
