# Generated by Django 2.2.1 on 2019-05-09 11:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0008_zipcodepolygon'),
    ]

    operations = [
        migrations.CreateModel(
            name='USACensusZip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_population', models.PositiveIntegerField()),
                ('number_of_households', models.PositiveIntegerField()),
                ('zipcode', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='USACensusPopulationByAge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_age', models.IntegerField()),
                ('end_age', models.IntegerField()),
                ('population_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('usa_census_zip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='age_segments', to='geo.USACensusZip')),
            ],
        ),
        migrations.CreateModel(
            name='USACensusIncomeDistribution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_start', models.IntegerField()),
                ('income_end', models.IntegerField()),
                ('income_distribution_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('usa_census_zip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='income_distributions', to='geo.USACensusZip')),
            ],
        ),
        migrations.CreateModel(
            name='USACensusHouseholdByType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('household_type', models.CharField(choices=[('Married', 'Married'), ('Single Female', 'Single Female'), ('Single Male', 'Single Male'), ('One Person', 'One Person'), ('Non-Family', 'Non-Family')], max_length=20)),
                ('household_percentage', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('usa_census_zip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='households', to='geo.USACensusZip')),
            ],
        ),
    ]
