# Generated by Django 2.2.1 on 2019-05-24 02:31

from django.db import migrations, models
import jsonfield.fields


def split_previously_imported_centers(apps, schema_editor):
    # Split "properties => center" into "lat" and "lon" fields

    Zipcode = apps.get_model("geo", "Zipcode")
    for zipcode in Zipcode.objects.all():
        if zipcode.properties:
            properties = dict(zipcode.properties)
            center = properties.get("center", {})

            if center is not None:
                zipcode.lon = center[0]
                zipcode.lat = center[1]
                zipcode.save()


class Migration(migrations.Migration):

    dependencies = [
        (
            "geo",
            "0009_usacensushouseholdbytype_usacensusincomedistribution_usacensuspopulationbyage_usacensuszip",
        )
    ]

    operations = [
        migrations.RenameModel("ZipcodePolygon", "Zipcode"),
        migrations.AddField(
            model_name="zipcode",
            name="lat",
            field=models.DecimalField(
                decimal_places=6,
                default=None,
                help_text="Latitude of zipcode center",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="zipcode",
            name="lon",
            field=models.DecimalField(
                decimal_places=6,
                default=None,
                help_text="Longitude of zipcode center",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="zipcode",
            name="land_area",
            field=models.FloatField(default=0, help_text="Land area in square miles"),
        ),
        migrations.AddField(
            model_name="zipcode",
            name="water_area",
            field=models.FloatField(default=0, help_text="Water area in square miles"),
        ),
        migrations.RunPython(split_previously_imported_centers),
    ]
