# Generated by Django 2.2.1 on 2019-05-24 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0010_rename_zipcodepolygon_to_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='zipcode',
            name='properties',
        ),
    ]
