# Generated by Django 2.2.1 on 2019-05-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0011_drop_properties_from_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='zipcode',
            name='has_population',
            field=models.BooleanField(null=True, help_text='Flag to identify dead zipcodes, based on Atlas service'),
        ),
    ]
