# Generated by Django 2.2.5 on 2019-09-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Localization",
            fields=[
                (
                    "key",
                    models.CharField(
                        help_text="A unique identifier for strings.",
                        max_length=255,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("en_us", models.TextField(help_text="English", max_length=2000)),
            ],
        )
    ]
