# Generated by Django 2.2.5 on 2019-09-26 10:57

from django.db import migrations, models


def add_english(apps, schema_editor):
    LocalizationVersion = apps.get_model("web", "LocalizationVersion")
    localization_version = LocalizationVersion.objects.create(
        language="en_us", version="init"
    )
    localization_version.save()


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("web", "0001_Add_localization_table")]

    operations = [
        migrations.CreateModel(
            name="LocalizationVersion",
            fields=[
                (
                    "language",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                (
                    "version",
                    models.CharField(
                        help_text="Version of Localization", max_length=50
                    ),
                ),
            ],
        ),
        migrations.RunPython(add_english, do_nothing),
    ]
