# Generated by Django 2.1.8 on 2019-04-23 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0003_auto_20190423_1624'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Company Name', max_length=250)),
                ('account_type', models.IntegerField(choices=[(1, 'Property Owner'), (2, 'Asset Manager'), (3, 'Property Manager'), (4, 'Remarkably')], help_text='Account Type')),
                ('address', models.ForeignKey(help_text='Address', on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='geo.Address')),
            ],
        ),
    ]
