# Generated by Django 2.1.8 on 2019-04-24 14:28

from django.db import migrations, models
import django.db.models.deletion


def set_account_for_existing_users(apps, schema_editor):
    Address = apps.get_model('geo', 'Address')
    Account = apps.get_model('users', 'Account')
    User = apps.get_model('users', 'User')

    address = Address.objects.create(
        street_address_1="2284 W. Commodore Way, Suite 200",
        city="Seattle",
        state="WA",
        zip_code=98199,
        country="US"
    )
    account = Account.objects.create(
        company_name='Remarkably',
        address=address,
        account_type=4,
    )
    User.objects.all().update(account=account)


def do_nothing(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account',
            field=models.ForeignKey(blank=True, null=True, related_name='users', on_delete=django.db.models.deletion.PROTECT, to='users.Account'),
        ),
        migrations.RunPython(set_account_for_existing_users, do_nothing),
    ]
