# Generated by Django 2.2.1 on 2019-05-14 15:45

from django.db import migrations, models
import remark.users.models
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=stdimage.models.StdImageField(blank=True, default='', help_text='A full-resolution user avatar.<br/>Resized variants (100x100, 36x36) will also be created on Amazon S3.', null=True, upload_to=remark.users.models.avatar_media_path),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
