# Generated by Django 2.2.3 on 2019-08-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20190620_1904")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_show_tutorial",
            field=models.BooleanField(
                default=True, help_text="Should there be tutorial showing"
            ),
        )
    ]
