# Generated by Django 2.2.3 on 2019-08-07 11:19
import datetime

from django.db import migrations, models
from django.utils import timezone


def update_existing_users(apps, schema_editor):
    User = apps.get_model("users", "User")
    activated = datetime.datetime.now(timezone.utc)
    User.objects.all().update(activated=activated)


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [("users", "0006_auto_20190620_1904")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="activated",
            field=models.DateTimeField(
                blank=True,
                default=None,
                help_text="Date when the user activated their account.",
                null=True,
            ),
        ),
        migrations.RunPython(update_existing_users, noop),
    ]
