# Generated by Django 2.2.5 on 2019-10-02 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("users", "0008_add_activated_fields")]

    operations = [
        migrations.AddField(
            model_name="user",
            name="invited",
            field=models.DateTimeField(
                blank=True, default=None, help_text="Date when user invited", null=True
            ),
        )
    ]
