# Generated by Django 2.2.5 on 2019-10-14 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0072_auto_20190919_2041'),
        ('users', '0009_Add_invited_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='report_projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
