# Generated by Django 2.2.8 on 2019-12-27 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0078_merge_20191212_2246'),
        ('users', '0010_user_report_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='report_projects',
        ),
        migrations.AddField(
            model_name='user',
            name='unsubscribed_projects',
            field=models.ManyToManyField(related_name='unsubscribed_users', to='projects.Project'),
        ),
    ]
