
KPI_NAMES = {
    "leased" : "Leased",
    "retention" : "Retention",
    "occupied" : "Occupied",
    "app": "Lease Applications / Volume of APP",
    "cds": "Cancellations & Denials",
    "renew" : "Notices to Renew",
    "vacate" : "Notices to Vacate",
    "move_ins" : "Move Ins",
    "move_outs" : "Move Outs",
    "investment": "Campaign Investment",
    # "estimated_revenue_change": "Estimated Revenue Change", # "estimated_revenue_gain" ???
    # "": "Campaign Return on Marketing Investment",
    # "": "Leased Unit Change", # "delta_leases" ???
    "acq_investment": "Acquisition Investment",
    # "": "Est. Acquired Leasing Revenue",
    "acq_romi": "Acquisition ROMI",
    "lease_renewals": "Lease Renewals",
    "ret_investment": "Retention Investment",
    # "": "Est. Retained Leasing Revenue",
    "ret_romi": "Retention ROMI",
    "usv_exe": "USV > EXE",
    # "cds_rate": "Cancellation & Denial Rate", ???
    "lowest_monthly_rent": "Cost Per EXE / Lowest Monthly Rent",
    "usv": "Volume of USV",
    "inq": "Volume of INQ",
    "tou": "Volume of TOU",
    "exe": "Volume of EXE",
    "usv_inq": "USV > INQ",
    "inq_tou": "INQ > TOU",
    "tou_app": "TOU > APP",
    "app_exe": "APP > EXE",
    "cost_per_usv": "Cost per USV",
    "cost_per_inq": "Cost per INQ",
    "cost_per_tou": "Cost per TOU",
    "cost_per_app": "Cost per APP",
    "cost_per_exe": "Cost per EXE",
}
